// Generated by OutWit.Cloud.Documents.Generator 1.0.0 from OutWit.Controller.CalculiX.Model 0.2.1.
// Do not edit: regenerate from the model assembly.
//
// OmnibusCloud job document vocabulary: sweep
//
// Every struct below is a published document type. Fill one in, then
// to_parameter_json() is the job request parameter ({"kind":"document",...})
// to place into the request's positional parameter list. Wire convention:
// camelCase keys, enum member names as strings, empty optionals omitted so
// the server applies its own defaults. UUIDs and timestamps travel as text
// (canonical UUID, ISO 8601). Header-only, C++17, standard library only.
#ifndef OMNIBUSCLOUD_DOCUMENTS_SWEEP_HPP
#define OMNIBUSCLOUD_DOCUMENTS_SWEEP_HPP

#include <charconv>
#include <cmath>
#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <type_traits>
#include <vector>

namespace omnibuscloud::documents::sweep {

inline constexpr std::string_view component = "sweep";

namespace detail {

// Minimal JSON writer: enough for the wire objects of this vocabulary.
class json_writer {
public:
    void begin_object() { separator(); out_ += '{'; first_.push_back(true); }
    void end_object() { out_ += '}'; first_.pop_back(); }
    void begin_array() { separator(); out_ += '['; first_.push_back(true); }
    void end_array() { out_ += ']'; first_.pop_back(); }

    void key(std::string_view name) {
        separator();
        write_string(name);
        out_ += ':';
        first_.back() = true;
    }

    void null_value() { separator(); out_ += "null"; }
    void value(bool v) { separator(); out_ += v ? "true" : "false"; }
    void value(std::string_view v) { separator(); write_string(v); }
    void value(const char* v) { value(std::string_view(v)); }
    void value(const std::string& v) { value(std::string_view(v)); }

    template <class T, std::enable_if_t<std::is_integral_v<T> && !std::is_same_v<T, bool>, int> = 0>
    void value(T v) {
        separator();
        char buffer[32];
        auto result = std::to_chars(buffer, buffer + sizeof(buffer), v);
        out_.append(buffer, result.ptr);
    }

    template <class T, std::enable_if_t<std::is_floating_point_v<T>, int> = 0>
    void value(T v) {
        if (!std::isfinite(v))
            throw std::invalid_argument("JSON has no representation for non-finite numbers");
        separator();
        char buffer[64];
        auto result = std::to_chars(buffer, buffer + sizeof(buffer), v);
        out_.append(buffer, result.ptr);
    }

    const std::string& str() const { return out_; }

private:
    void separator() {
        if (first_.empty())
            return;
        if (!first_.back())
            out_ += ',';
        first_.back() = false;
    }

    void write_string(std::string_view text) {
        static constexpr char hex[] = "0123456789abcdef";
        out_ += '"';
        for (unsigned char c : text) {
            switch (c) {
                case '"': out_ += "\\\""; break;
                case '\\': out_ += "\\\\"; break;
                case '\b': out_ += "\\b"; break;
                case '\f': out_ += "\\f"; break;
                case '\n': out_ += "\\n"; break;
                case '\r': out_ += "\\r"; break;
                case '\t': out_ += "\\t"; break;
                default:
                    if (c < 0x20) {
                        out_ += "\\u00";
                        out_ += hex[c >> 4];
                        out_ += hex[c & 0xF];
                    } else {
                        out_ += static_cast<char>(c);
                    }
            }
        }
        out_ += '"';
    }

    std::string out_;
    std::vector<bool> first_;
};

} // namespace detail

/// Document type sweep.resultIndexEntry@1.
struct sweep_result_index_entry {
    static constexpr std::string_view type_id = "sweep.resultIndexEntry@1";

    std::optional<int32_t> variant_index;
    std::optional<bool> succeeded;
    std::optional<std::string> frd_blob_id;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (variant_index) {
            w.key("variantIndex");
            w.value((*variant_index));
        }
        if (succeeded) {
            w.key("succeeded");
            w.value((*succeeded));
        }
        if (frd_blob_id) {
            w.key("frdBlobId");
            w.value((*frd_blob_id));
        }
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"sweep.resultIndexEntry@1\",\"value\":") + to_json() + "}";
    }
};

/// Document type sweep.state@1.
struct sweep_state {
    static constexpr std::string_view type_id = "sweep.state@1";

    std::optional<int32_t> chunk_index;
    std::optional<int32_t> next_variant_ordinal;
    std::optional<int32_t> completed_count;
    std::optional<int32_t> failed_count;
    std::optional<std::string> manifest_blob_id;
    std::vector<sweep_result_index_entry> results;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (chunk_index) {
            w.key("chunkIndex");
            w.value((*chunk_index));
        }
        if (next_variant_ordinal) {
            w.key("nextVariantOrdinal");
            w.value((*next_variant_ordinal));
        }
        if (completed_count) {
            w.key("completedCount");
            w.value((*completed_count));
        }
        if (failed_count) {
            w.key("failedCount");
            w.value((*failed_count));
        }
        if (manifest_blob_id) {
            w.key("manifestBlobId");
            w.value((*manifest_blob_id));
        }
        w.key("results");
        w.begin_array();
        for (const auto& item0 : results) {
            item0.write_json(w);
        }
        w.end_array();
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"sweep.state@1\",\"value\":") + to_json() + "}";
    }
};

/// Every published type id of the component.
inline constexpr std::string_view type_ids[] = {
    "sweep.resultIndexEntry@1",
    "sweep.state@1",
};

} // namespace omnibuscloud::documents::sweep

#endif // OMNIBUSCLOUD_DOCUMENTS_SWEEP_HPP
