//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWit.Controller.Grid.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OutWit.Controller.Grid.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filed to get parameter {0} for activity {1}.
        /// </summary>
        internal static string FailedToGetParameterValueError {
            get {
                return ResourceManager.GetString("FailedToGetParameterValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filed to set return value {0} for activity {1}.
        /// </summary>
        internal static string FailedToSetReturnValueError {
            get {
                return ResourceManager.GetString("FailedToSetReturnValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create instance of activity {0} with parameters {1}.
        /// </summary>
        internal static string WitActivityCreateError {
            get {
                return ResourceManager.GetString("WitActivityCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected array or reference to variable.
        /// </summary>
        internal static string WitActivityExpectedArrayError {
            get {
                return ResourceManager.GetString("WitActivityExpectedArrayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected boolean cnstant or reference to variable.
        /// </summary>
        internal static string WitActivityExpectedBooleanError {
            get {
                return ResourceManager.GetString("WitActivityExpectedBooleanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected condition.
        /// </summary>
        internal static string WitActivityExpectedConditionError {
            get {
                return ResourceManager.GetString("WitActivityExpectedConditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected numeric constant or reference to variable.
        /// </summary>
        internal static string WitActivityExpectedNumericError {
            get {
                return ResourceManager.GetString("WitActivityExpectedNumericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected reference to variable.
        /// </summary>
        internal static string WitActivityExpectedReferenceError {
            get {
                return ResourceManager.GetString("WitActivityExpectedReferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected string constant or reference to variable.
        /// </summary>
        internal static string WitActivityExpectedStringError {
            get {
                return ResourceManager.GetString("WitActivityExpectedStringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually triggered exception for activity {0}.
        /// </summary>
        internal static string WitActivityManualError {
            get {
                return ResourceManager.GetString("WitActivityManualError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create instance of activity {0}.
        /// </summary>
        internal static string WitActivityNoParametersCreateError {
            get {
                return ResourceManager.GetString("WitActivityNoParametersCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} for activity {1} not supported.
        /// </summary>
        internal static string WitActivityWrongParameterError {
            get {
                return ResourceManager.GetString("WitActivityWrongParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameters for activity {0} not supported, expected number of parameters: {1}.
        /// </summary>
        internal static string WitActivityWrongParametersError {
            get {
                return ResourceManager.GetString("WitActivityWrongParametersError", resourceCulture);
            }
        }
    }
}
