using System.Runtime.InteropServices;
using System.Text.Json;
using OutWit.Controller.Visualization.ParaView.Model;
using OutWit.Controller.Visualization.ParaView.Runtime;
using OutWit.Controller.Visualization.ParaView.Tests.Mock;

namespace OutWit.Controller.Visualization.ParaView.Tests.Utils;

/// <summary>
/// The fixture corpus generated by <c>RuntimeTools/generate_fixtures.py</c> with the pinned ParaView
/// (committed under Fixtures/Corpus): real states saved by pvpython with logical data paths, the small
/// data files, and the package metadata each state needs (which files, which series, which timesteps).
/// Also locates a real pvpython for the runtime tests (OUTWIT_PVPYTHON, then @Prerequisites/paraview).
/// </summary>
internal static class ParaViewCorpus
{
    #region Constants

    public const string VTI_CONTOUR = "vti_contour.pvsm";

    public const string VTI_VOLUME = "vti_volume.pvsm";

    public const string VTU_SLICE_CLIP_GLYPH = "vtu_slice_clip_glyph.pvsm";

    public const string VTR_SURFACE = "vtr_surface.pvsm";

    public const string PVD_SERIES = "pvd_series.pvsm";

    public const string FILE_SERIES = "file_series.pvsm";

    public const string SPHERE_STATIC = "sphere_static.pvsm";

    private const string SERIES_GROUP = "series";

    #endregion

    #region Functions

    /// <summary>Root of the committed corpus in the test output.</summary>
    public static string Root => Path.Combine(AppContext.BaseDirectory, "Fixtures", "Corpus");

    /// <summary>All state file names of the corpus.</summary>
    public static IReadOnlyList<string> States => Directory.GetFiles(Path.Combine(Root, "states"), "*.pvsm").Select(Path.GetFileName).Select(me => me!).Order().ToList();

    /// <summary>The ParaView version the corpus was generated with, from manifest.json.</summary>
    public static string GeneratedWith()
    {
        using var document = JsonDocument.Parse(File.ReadAllText(Path.Combine(Root, "manifest.json")));
        return document.RootElement.GetProperty("paraview").GetString() ?? string.Empty;
    }

    /// <summary>Absolute path of a corpus state.</summary>
    public static string StatePath(string stateName)
    {
        return Path.Combine(Root, "states", stateName);
    }

    /// <summary>
    /// The logical data files a state references, with the series metadata a producing plugin would attach.
    /// </summary>
    /// <param name="stateName">Corpus state file name.</param>
    /// <returns>(logicalPath, role, seriesGroup, timestepIndices, ordinal) per file.</returns>
    public static IReadOnlyList<(string LogicalPath, ParaViewAttachmentRole Role, string SeriesGroup, int[] TimestepIndices, int Ordinal)> FilesOf(string stateName)
    {
        return stateName switch
        {
            VTI_CONTOUR or VTI_VOLUME => [("data/wavelet.vti", ParaViewAttachmentRole.ReaderInput, "", [], 0)],
            VTU_SLICE_CLIP_GLYPH => [("data/tets.vtu", ParaViewAttachmentRole.ReaderInput, "", [], 0)],
            VTR_SURFACE => [("data/grid.vtr", ParaViewAttachmentRole.ReaderInput, "", [], 0)],
            PVD_SERIES =>
            [
                ("data/series/series.pvd", ParaViewAttachmentRole.SeriesIndex, SERIES_GROUP, [], 0),
                .. Enumerable.Range(0, 5).Select(i => ($"data/series/series_{i:D3}.vti", ParaViewAttachmentRole.ReaderInput, SERIES_GROUP, new[] { i }, i))
            ],
            FILE_SERIES => [.. Enumerable.Range(0, 5).Select(i => ($"data/series/series_{i:D3}.vti", ParaViewAttachmentRole.ReaderInput, SERIES_GROUP, new[] { i }, i))],
            SPHERE_STATIC => [],
            _ => throw new ArgumentOutOfRangeException(nameof(stateName), stateName, "unknown corpus state")
        };
    }

    /// <summary>The producer timeline of a state (what the plugin reads from the TimeKeeper).</summary>
    public static double[] TimelineOf(string stateName)
    {
        return stateName switch
        {
            PVD_SERIES => [0.0, 0.5, 1.0, 1.5, 2.0],
            FILE_SERIES => [0, 1, 2, 3, 4],
            _ => []
        };
    }

    /// <summary>
    /// Builds the package of a corpus state in a fresh directory: registers the data files and the state
    /// in the blob service and returns the scene reference with the series metadata.
    /// </summary>
    public static (ParaViewSceneRefData Scene, ParaViewPackageBuilder Package) BuildScene(string stateName, string directory, ParaViewTestBlobService blobs)
    {
        var package = new ParaViewPackageBuilder(directory, blobs);
        foreach (var (logicalPath, role, group, timesteps, ordinal) in FilesOf(stateName))
            package.AddFile(logicalPath, File.ReadAllBytes(Path.Combine(Root, logicalPath.Replace('/', Path.DirectorySeparatorChar))), role, group, timesteps.Length == 0 ? null : timesteps, ordinal);

        var scene = package.BuildScene(File.ReadAllText(StatePath(stateName)), timestepValues: TimelineOf(stateName));
        return (scene, package);
    }

    /// <summary>
    /// Finds a real pvpython for the runtime tests: OUTWIT_PVPYTHON, then the current platform's folder under
    /// @Prerequisites/paraview, then any extracted official distribution under @Prerequisites/paraview/full.
    /// </summary>
    /// <returns>The pvpython path or null.</returns>
    public static string? FindPvpython()
    {
        var configured = Environment.GetEnvironmentVariable(ParaViewBinaryResolver.ENV_PVPYTHON_PATH);
        if (!string.IsNullOrWhiteSpace(configured) && File.Exists(configured))
            return configured;

        var solutionRoot = ParaViewTestPaths.FindSolutionRoot();
        if (solutionRoot == null)
            return null;

        var prerequisites = Path.Combine(solutionRoot, "@Prerequisites", "paraview");
        var folder = ParaViewBinaryResolver.ResolveCurrentRuntimeFolder();
        var candidates = new List<string>();
        if (folder != null)
            candidates.Add(Path.Combine(prerequisites, folder));

        var full = Path.Combine(prerequisites, "full");
        if (Directory.Exists(full))
            candidates.AddRange(Directory.GetDirectories(full).Where(me => OnThisPlatform(Path.GetFileName(me))));

        return candidates.Where(Directory.Exists).Select(ParaViewBinaryResolver.FindExecutable).FirstOrDefault(me => me != null);
    }

    #endregion

    #region Tools

    private static bool OnThisPlatform(string distributionName)
    {
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            return distributionName.Contains("Windows", StringComparison.OrdinalIgnoreCase);

        if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
            return distributionName.Contains("Linux", StringComparison.OrdinalIgnoreCase);

        return distributionName.Contains("OSX", StringComparison.OrdinalIgnoreCase);
    }

    #endregion
}
