Job:BakeAndRenderFramesCycles(RenderSceneRef:scene, Int:startFrame, Int:endFrame, RenderOptions:options, RenderBakeOptions:bakeOptions)
{
    RenderSceneRef:baked = Grid.Delegate() => Render.BakeSimulation(scene, startFrame, endFrame, bakeOptions);

    Blob:blend = Render.BuildBlendFromRefs(baked);
    RenderTaskBatchCollection:tasks = Render.SplitBatched(blend, startFrame, endFrame, options);

    RenderResultBatchCollection:rendered = Grid.ForEach(task in tasks)
        => Render.FrameBatch.Cycles(task);

    BlobCollection:result = Render.Collect(rendered, options);
}
