Job:RenderStillTiledEevee(RenderSceneRef:scene, Int:frame, Int:tilesX, Int:tilesY, RenderOptions:options, TileOptions:tileOptions)
{
    Blob:blend = Render.BuildBlendFromRefs(scene);
    RenderTaskBatchCollection:tasks = Render.SplitTilesBatched(blend, frame, tilesX, tilesY, options, tileOptions);

    RenderResultBatchCollection:rendered = Grid.ForEach(task in tasks)
        => Render.FrameBatch.Eevee(task);

    Blob:result = Render.CollectTiles(rendered, options, tileOptions);
}
