Job:RenderStillEevee(RenderSceneRef:scene, Int:frame, RenderOptions:options)
{
    Blob:blend = Render.BuildBlendFromRefs(scene);
    RenderTaskCollection:tasks = Render.Split(blend, frame, frame, options);

    RenderResultCollection:rendered = Grid.ForEach(task in tasks)
        => Render.Frame.Eevee(task);

    Blob:result = Render.CollectStill(rendered, options);
}
