Job:RenderStillTiledEevee(RenderSceneRef:scene, Int:frame, Int:tilesX, Int:tilesY, RenderOptions:options, TileOptions:tileOptions)
{
    Blob:blend = Render.BuildBlendFromRefs(scene);
    RenderTaskCollection:tasks = Render.SplitTiles(blend, frame, tilesX, tilesY, options, tileOptions);

    RenderResultCollection:rendered = Grid.ForEach(task in tasks)
        => Render.Frame.Eevee(task);

    Blob:result = Render.CollectTiles(rendered, options, tileOptions);
}
