Job:RenderFramesGreasePencil(RenderSceneRef:scene, Int:startFrame, Int:endFrame, RenderOptions:options)
{
    Blob:blend = Render.BuildBlendFromRefs(scene);
    RenderTaskBatchCollection:tasks = Render.SplitBatched(blend, startFrame, endFrame, options);

    RenderResultBatchCollection:rendered = Grid.ForEach(task in tasks)
        => Render.FrameBatch.GreasePencil(task);

    BlobCollection:result = Render.Collect(rendered, options);
}
