Job:RenderStill(RenderSceneRef:scene, Int:frame, RenderOptions:options)
{
    Blob:blend = Render.BuildBlendFromRefs(scene);
    RenderTaskBatchCollection:tasks = Render.SplitBatched(blend, frame, frame, options);

    RenderResultBatchCollection:rendered = Grid.ForEach(task in tasks)
        => Render.FrameBatch(task);

    Blob:result = Render.CollectStill(rendered, options);
}
