Job:RenderDccSceneFrames(DccScene:scene, Int:startFrame, Int:endFrame, RenderOptions:options)
{
    Blob:blend = Render.BuildBlendFromDccScene(scene);
    Render.ClearScene(scene);

    RenderTaskBatchCollection:tasks = Render.SplitBatched(blend, startFrame, endFrame, options);

    RenderResultBatchCollection:rendered = Grid.ForEach(task in tasks)
        => Render.FrameBatch(task);

    BlobCollection:result = Render.Collect(rendered, options);
}
