Job:RenderVideoEevee(RenderSceneRef:scene, Int:startFrame, Int:endFrame, RenderOptions:options, VideoOptions:video)
{
    Blob:blend = Render.BuildBlendFromRefs(scene);
    RenderTaskBatchCollection:tasks = Render.SplitBatched(blend, startFrame, endFrame, options);

    RenderResultBatchCollection:rendered = Grid.ForEach(task in tasks)
        => Render.FrameBatch.Eevee(task);

    BlobCollection:frames = Render.Collect(rendered, options);
    Blob:result = Render.EncodeVideo(frames, video);
}
