Job:RenderSceneStillTiled(RenderScene:scene, Int:frame, Int:tilesX, Int:tilesY, RenderOptions:options, TileOptions:tileOptions)
{
    Blob:blend = Render.BuildBlend(scene);

    RenderTaskBatchCollection:tasks = Render.SplitTilesBatched(blend, frame, tilesX, tilesY, options, tileOptions);

    RenderResultBatchCollection:rendered = Grid.ForEach(task in tasks)
        => Render.FrameBatch(task);

    Blob:result = Render.CollectTiles(rendered, options, tileOptions);
}
