using MemoryPack;
using OutWit.Common.Abstract;
using OutWit.Common.Values;

namespace OutWit.Controller.Render.Model;

/// <summary>
/// Self-contained description of a single render task.
/// Generated by Render.Split, consumed by Render.Frame.
/// Contains everything needed to render one frame or tile.
/// Shared between SDK, controller, and plugins.
/// </summary>
[MemoryPackable]
public partial class RenderTaskData : ModelBase
{
    #region Properties

    /// <summary>
    /// Blob identifier of the .blend scene file.
    /// </summary>
    public Guid SceneBlobId { get; set; }

    /// <summary>
    /// Frame number to render.
    /// </summary>
    public int Frame { get; set; }

    /// <summary>
    /// Tile region — normalized X minimum (0.0-1.0). Default 0 = full frame.
    /// </summary>
    public float TileMinX { get; set; }

    /// <summary>
    /// Tile region — normalized X maximum (0.0-1.0). Default 1 = full frame.
    /// </summary>
    public float TileMaxX { get; set; } = 1f;

    /// <summary>
    /// Tile region — normalized Y minimum (0.0-1.0). Default 0 = full frame.
    /// </summary>
    public float TileMinY { get; set; }

    /// <summary>
    /// Tile region — normalized Y maximum (0.0-1.0). Default 1 = full frame.
    /// </summary>
    public float TileMaxY { get; set; } = 1f;

    /// <summary>
    /// Task index for ordering results (Grid.ForEach is async).
    /// </summary>
    public int TaskIndex { get; set; }

    /// <summary>
    /// Actual rendered X minimum including overlap expansion.
    /// When not set explicitly, the logical tile bounds are used.
    /// </summary>
    public float RenderMinX { get; set; }

    /// <summary>
    /// Actual rendered X maximum including overlap expansion.
    /// When not set explicitly, the logical tile bounds are used.
    /// </summary>
    public float RenderMaxX { get; set; } = 1f;

    /// <summary>
    /// Actual rendered Y minimum including overlap expansion.
    /// When not set explicitly, the logical tile bounds are used.
    /// </summary>
    public float RenderMinY { get; set; }

    /// <summary>
    /// Actual rendered Y maximum including overlap expansion.
    /// When not set explicitly, the logical tile bounds are used.
    /// </summary>
    public float RenderMaxY { get; set; } = 1f;

    /// <summary>
    /// Render options for this task.
    /// </summary>
    [MemoryPackAllowSerialize]
    public RenderOptionsData Options { get; set; } = new();

    #endregion

    #region Functions

    /// <summary>
    /// Returns true if this task renders the full frame (no tile subdivision).
    /// </summary>
    [MemoryPackIgnore]
    public bool IsFullFrame => TileMinX == 0f && TileMaxX == 1f && TileMinY == 0f && TileMaxY == 1f;

    [MemoryPackIgnore]
    public bool HasExplicitRenderBounds => RenderMinX != 0f || RenderMaxX != 1f || RenderMinY != 0f || RenderMaxY != 1f;

    [MemoryPackIgnore]
    public float EffectiveRenderMinX => HasExplicitRenderBounds ? RenderMinX : TileMinX;

    [MemoryPackIgnore]
    public float EffectiveRenderMaxX => HasExplicitRenderBounds ? RenderMaxX : TileMaxX;

    [MemoryPackIgnore]
    public float EffectiveRenderMinY => HasExplicitRenderBounds ? RenderMinY : TileMinY;

    [MemoryPackIgnore]
    public float EffectiveRenderMaxY => HasExplicitRenderBounds ? RenderMaxY : TileMaxY;

    #endregion

    #region ModelBase

    public override bool Is(ModelBase modelBase, double tolerance = DEFAULT_TOLERANCE)
    {
        if (modelBase is not RenderTaskData other)
            return false;

        return SceneBlobId.Is(other.SceneBlobId)
               && Frame.Is(other.Frame)
               && TileMinX.Is(other.TileMinX, tolerance)
               && TileMaxX.Is(other.TileMaxX, tolerance)
               && TileMinY.Is(other.TileMinY, tolerance)
               && TileMaxY.Is(other.TileMaxY, tolerance)
               && RenderMinX.Is(other.RenderMinX, tolerance)
               && RenderMaxX.Is(other.RenderMaxX, tolerance)
               && RenderMinY.Is(other.RenderMinY, tolerance)
               && RenderMaxY.Is(other.RenderMaxY, tolerance)
               && TaskIndex.Is(other.TaskIndex)
               && Options.Is(other.Options, tolerance);
    }

    public override ModelBase Clone()
    {
        return new RenderTaskData
        {
            SceneBlobId = SceneBlobId,
            Frame = Frame,
            TileMinX = TileMinX,
            TileMaxX = TileMaxX,
            TileMinY = TileMinY,
            TileMaxY = TileMaxY,
            RenderMinX = RenderMinX,
            RenderMaxX = RenderMaxX,
            RenderMinY = RenderMinY,
            RenderMaxY = RenderMaxY,
            TaskIndex = TaskIndex,
            Options = (RenderOptionsData)Options.Clone()
        };
    }

    #endregion
}
