# Generated by OutWit.Cloud.Documents.Generator 1.0.0 from OutWit.Controller.Sweep.Model 2.0.0.
# Do not edit: regenerate from the model assembly.
#
# OmnibusCloud job document vocabulary: sweep
#
# Every dataclass below is a published document type. Build one, then
# to_parameter() gives the job request parameter ({"kind": "document", ...})
# to place into the request's positional parameter list; from_json() reads
# a value document's "value" back into the typed object. Wire convention:
# camelCase keys, enum member names as strings, None properties omitted.
# Optional fields left as None are omitted, which lets the server apply its
# own defaults; a field the server marks required has no default here.
#
# Standard library only, Python 3.10+ (keyword-only dataclasses); no OmnibusCloud
# SDK import is needed to use it.
from __future__ import annotations

import datetime as _datetime
import enum as _enum
import re as _re
import uuid as _uuid
from dataclasses import dataclass as _dataclass
from dataclasses import field as _field
from typing import Any as _Any
from typing import ClassVar as _ClassVar
from typing import Optional as _Optional

COMPONENT = "sweep"
"""The component whose vocabulary this module binds."""

TYPE_IDS = (
    "sweep.artifact@1",
    "sweep.resultIndexEntry@2",
    "sweep.state@2",
)
"""Every published type id of the component."""


_FRACTION = _re.compile(r"(\.\d{6})\d+")


def _omit_none(values: dict) -> dict:
    return {key: value for key, value in values.items() if value is not None}


def _enum_to_json(value: _Any) -> _Any:
    return value.value if isinstance(value, _enum.Enum) else value


def _enum_from_json(enum_type: type, value: _Any) -> _Any:
    # A member name this binding does not know (newer server) is kept as text.
    try:
        return enum_type(value)
    except ValueError:
        return value


def _uuid_to_json(value: _Any) -> str:
    return str(value)


def _uuid_from_json(value: _Any) -> _uuid.UUID:
    return value if isinstance(value, _uuid.UUID) else _uuid.UUID(str(value))


def _datetime_to_json(value: _Any) -> str:
    # The server's form: ISO 8601, fraction only when non-zero and without
    # trailing zeros, 'Z' for UTC, offset otherwise, nothing for naive values.
    if isinstance(value, str):
        return value
    text = value.strftime("%Y-%m-%dT%H:%M:%S")
    if value.microsecond:
        text += "." + f"{value.microsecond:06d}".rstrip("0")
    offset = value.utcoffset()
    if offset is None:
        return text
    if offset == _datetime.timedelta(0):
        return text + "Z"
    total = int(offset.total_seconds())
    sign = "+" if total >= 0 else "-"
    total = abs(total)
    return text + f"{sign}{total // 3600:02d}:{(total % 3600) // 60:02d}"


def _datetime_from_json(value: _Any) -> _datetime.datetime:
    if isinstance(value, _datetime.datetime):
        return value
    text = str(value)
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    # .NET writes seven fractional digits; Python parses at most six.
    return _datetime.datetime.fromisoformat(_FRACTION.sub(r"\1", text))


class SweepArtifactKind(str, _enum.Enum):
    """Wire values of OutWit.Controller.Sweep.Model.SweepArtifactKind."""

    CalculiXFrd = "CalculiXFrd"
    CalculiXDat = "CalculiXDat"
    OpenFOAMCase = "OpenFOAMCase"


class SweepOutcome(str, _enum.Enum):
    """Wire values of OutWit.Controller.Sweep.Model.SweepOutcome."""

    Succeeded = "Succeeded"
    Failed = "Failed"
    Refused = "Refused"


@_dataclass(kw_only=True)
class SweepArtifact:
    """Document type sweep.artifact@1."""

    TYPE_ID: _ClassVar[str] = "sweep.artifact@1"
    """The published type id this class binds."""

    kind: _Optional[SweepArtifactKind] = None
    blob_id: _Optional[_uuid.UUID] = None
    bytes: _Optional[int] = None

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "kind": (None if self.kind is None else _enum_to_json(self.kind)),
            "blobId": (None if self.blob_id is None else _uuid_to_json(self.blob_id)),
            "bytes": self.bytes,
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "SweepArtifact":
        """Reads the wire object of a value document."""
        return cls(
            kind=(None if data.get("kind") is None else _enum_from_json(SweepArtifactKind, data.get("kind"))),
            blob_id=(None if data.get("blobId") is None else _uuid_from_json(data.get("blobId"))),
            bytes=data.get("bytes"),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class SweepResultIndexEntryV2:
    """Document type sweep.resultIndexEntry@2."""

    TYPE_ID: _ClassVar[str] = "sweep.resultIndexEntry@2"
    """The published type id this class binds."""

    variant_index: _Optional[int] = None
    outcome: _Optional[SweepOutcome] = None
    label: _Optional[str] = None
    artifacts: list[SweepArtifact] = _field(default_factory=list)

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "variantIndex": self.variant_index,
            "outcome": (None if self.outcome is None else _enum_to_json(self.outcome)),
            "label": self.label,
            "artifacts": (None if self.artifacts is None else [item0.to_json() for item0 in self.artifacts]),
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "SweepResultIndexEntryV2":
        """Reads the wire object of a value document."""
        return cls(
            variant_index=data.get("variantIndex"),
            outcome=(None if data.get("outcome") is None else _enum_from_json(SweepOutcome, data.get("outcome"))),
            label=data.get("label"),
            artifacts=([] if data.get("artifacts") is None else [(None if item0 is None else SweepArtifact.from_json(item0)) for item0 in data.get("artifacts")]),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class SweepStateV2:
    """Document type sweep.state@2."""

    TYPE_ID: _ClassVar[str] = "sweep.state@2"
    """The published type id this class binds."""

    chunk_index: _Optional[int] = None
    next_variant_ordinal: _Optional[int] = None
    succeeded_count: _Optional[int] = None
    failed_count: _Optional[int] = None
    refused_count: _Optional[int] = None
    manifest_blob_id: _Optional[_uuid.UUID] = None
    results: list[SweepResultIndexEntryV2] = _field(default_factory=list)

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "chunkIndex": self.chunk_index,
            "nextVariantOrdinal": self.next_variant_ordinal,
            "succeededCount": self.succeeded_count,
            "failedCount": self.failed_count,
            "refusedCount": self.refused_count,
            "manifestBlobId": (None if self.manifest_blob_id is None else _uuid_to_json(self.manifest_blob_id)),
            "results": (None if self.results is None else [item0.to_json() for item0 in self.results]),
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "SweepStateV2":
        """Reads the wire object of a value document."""
        return cls(
            chunk_index=data.get("chunkIndex"),
            next_variant_ordinal=data.get("nextVariantOrdinal"),
            succeeded_count=data.get("succeededCount"),
            failed_count=data.get("failedCount"),
            refused_count=data.get("refusedCount"),
            manifest_blob_id=(None if data.get("manifestBlobId") is None else _uuid_from_json(data.get("manifestBlobId"))),
            results=([] if data.get("results") is None else [(None if item0 is None else SweepResultIndexEntryV2.from_json(item0)) for item0 in data.get("results")]),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


DOCUMENT_TYPES = {
    "sweep.artifact@1": SweepArtifact,
    "sweep.resultIndexEntry@2": SweepResultIndexEntryV2,
    "sweep.state@2": SweepStateV2,
}
"""Type id -> dataclass, for reading value documents by their declared type."""


def from_value_document(document: dict[str, _Any]) -> _Any:
    """Reads a value document (schema v1) of a type this module binds; primitives pass through."""
    kind = document.get("kind")
    if kind == "null":
        return None
    if kind != "document":
        return document.get("value")
    type_id = document.get("type")
    binding = DOCUMENT_TYPES.get(type_id)
    if binding is None:
        raise KeyError(f"document type {type_id!r} is not part of the {COMPONENT} vocabulary")
    return binding.from_json(document.get("value") or {})


__all__ = [
    "COMPONENT",
    "TYPE_IDS",
    "DOCUMENT_TYPES",
    "from_value_document",
    "SweepArtifactKind",
    "SweepOutcome",
    "SweepArtifact",
    "SweepResultIndexEntryV2",
    "SweepStateV2",
]
