<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\Build\OutWit.Controller.Tests.props" />

  <ItemGroup>
    <ProjectReference Include="..\OutWit.Controller.Sweep\OutWit.Controller.Sweep.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ExcludedControllerModule Include="render.module" />
    <ExcludedControllerModule Include="renderdcc.module" />
    <ExcludedControllerModule Include="schwarz.module" />
    <ExcludedControllerModule Include="parareal.module" />
    <ExcludedControllerModule Include="calculix.module" />
  </ItemGroup>

</Project>
