// Generated by OutWit.Cloud.Documents.Generator 1.0.0 from OutWit.Controller.Render.Model 1.8.0.
// Do not edit: regenerate from the model assembly.
//
// OmnibusCloud job document vocabulary: render
//
// Every struct below is a published document type. Fill one in, then
// to_parameter_json() is the job request parameter ({"kind":"document",...})
// to place into the request's positional parameter list. Wire convention:
// camelCase keys, enum member names as strings, empty optionals omitted so
// the server applies its own defaults. UUIDs and timestamps travel as text
// (canonical UUID, ISO 8601). Header-only, C++17, standard library only.
#ifndef OMNIBUSCLOUD_DOCUMENTS_RENDER_HPP
#define OMNIBUSCLOUD_DOCUMENTS_RENDER_HPP

#include <charconv>
#include <cmath>
#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <type_traits>
#include <vector>

namespace omnibuscloud::documents::render {

inline constexpr std::string_view component = "render";

namespace detail {

// Minimal JSON writer: enough for the wire objects of this vocabulary.
class json_writer {
public:
    void begin_object() { separator(); out_ += '{'; first_.push_back(true); }
    void end_object() { out_ += '}'; first_.pop_back(); }
    void begin_array() { separator(); out_ += '['; first_.push_back(true); }
    void end_array() { out_ += ']'; first_.pop_back(); }

    void key(std::string_view name) {
        separator();
        write_string(name);
        out_ += ':';
        first_.back() = true;
    }

    void null_value() { separator(); out_ += "null"; }
    void value(bool v) { separator(); out_ += v ? "true" : "false"; }
    void value(std::string_view v) { separator(); write_string(v); }
    void value(const char* v) { value(std::string_view(v)); }
    void value(const std::string& v) { value(std::string_view(v)); }

    template <class T, std::enable_if_t<std::is_integral_v<T> && !std::is_same_v<T, bool>, int> = 0>
    void value(T v) {
        separator();
        char buffer[32];
        auto result = std::to_chars(buffer, buffer + sizeof(buffer), v);
        out_.append(buffer, result.ptr);
    }

    template <class T, std::enable_if_t<std::is_floating_point_v<T>, int> = 0>
    void value(T v) {
        if (!std::isfinite(v))
            throw std::invalid_argument("JSON has no representation for non-finite numbers");
        separator();
        char buffer[64];
        auto result = std::to_chars(buffer, buffer + sizeof(buffer), v);
        out_.append(buffer, result.ptr);
    }

    const std::string& str() const { return out_; }

private:
    void separator() {
        if (first_.empty())
            return;
        if (!first_.back())
            out_ += ',';
        first_.back() = false;
    }

    void write_string(std::string_view text) {
        static constexpr char hex[] = "0123456789abcdef";
        out_ += '"';
        for (unsigned char c : text) {
            switch (c) {
                case '"': out_ += "\\\""; break;
                case '\\': out_ += "\\\\"; break;
                case '\b': out_ += "\\b"; break;
                case '\f': out_ += "\\f"; break;
                case '\n': out_ += "\\n"; break;
                case '\r': out_ += "\\r"; break;
                case '\t': out_ += "\\t"; break;
                default:
                    if (c < 0x20) {
                        out_ += "\\u00";
                        out_ += hex[c >> 4];
                        out_ += hex[c & 0xF];
                    } else {
                        out_ += static_cast<char>(c);
                    }
            }
        }
        out_ += '"';
    }

    std::string out_;
    std::vector<bool> first_;
};

} // namespace detail

/// Output bit depth per channel (Blender's image_settings.color_depth).
enum class render_color_depth {
    /// Leave the scene/format default untouched (legacy behaviour).
    Default,
    /// 8-bit (PNG/JPEG).
    Eight,
    /// 16-bit (PNG, EXR half).
    Sixteen,
    /// 32-bit (EXR full float).
    ThirtyTwo,
};

/// The wire name of a render_color_depth value.
inline std::string_view to_string(render_color_depth value) noexcept {
    switch (value) {
        case render_color_depth::Default: return "Default";
        case render_color_depth::Eight: return "Eight";
        case render_color_depth::Sixteen: return "Sixteen";
        case render_color_depth::ThirtyTwo: return "ThirtyTwo";
    }
    return "";
}

/// Parses the wire name of a render_color_depth value; false when the name is unknown.
inline bool try_parse(std::string_view text, render_color_depth& value) noexcept {
    if (text == "Default") { value = render_color_depth::Default; return true; }
    if (text == "Eight") { value = render_color_depth::Eight; return true; }
    if (text == "Sixteen") { value = render_color_depth::Sixteen; return true; }
    if (text == "ThirtyTwo") { value = render_color_depth::ThirtyTwo; return true; }
    return false;
}

/// Output colour channels for a render.
enum class render_color_mode {
    /// Legacy behaviour: force RGB for PNG/JPEG, leave the scene default for EXR. Keeps old clients (which don't send a colour mode) rendering exactly as before.
    Default,
    /// RGB (no alpha).
    RGB,
    /// RGBA (with alpha) — needed for transparent renders / compositing.
    RGBA,
};

/// The wire name of a render_color_mode value.
inline std::string_view to_string(render_color_mode value) noexcept {
    switch (value) {
        case render_color_mode::Default: return "Default";
        case render_color_mode::RGB: return "RGB";
        case render_color_mode::RGBA: return "RGBA";
    }
    return "";
}

/// Parses the wire name of a render_color_mode value; false when the name is unknown.
inline bool try_parse(std::string_view text, render_color_mode& value) noexcept {
    if (text == "Default") { value = render_color_mode::Default; return true; }
    if (text == "RGB") { value = render_color_mode::RGB; return true; }
    if (text == "RGBA") { value = render_color_mode::RGBA; return true; }
    return false;
}

/// Render engine selection.
enum class render_engine {
    Cycles,
    Eevee,
    GreasePencil,
};

/// The wire name of a render_engine value.
inline std::string_view to_string(render_engine value) noexcept {
    switch (value) {
        case render_engine::Cycles: return "Cycles";
        case render_engine::Eevee: return "Eevee";
        case render_engine::GreasePencil: return "GreasePencil";
    }
    return "";
}

/// Parses the wire name of a render_engine value; false when the name is unknown.
inline bool try_parse(std::string_view text, render_engine& value) noexcept {
    if (text == "Cycles") { value = render_engine::Cycles; return true; }
    if (text == "Eevee") { value = render_engine::Eevee; return true; }
    if (text == "GreasePencil") { value = render_engine::GreasePencil; return true; }
    return false;
}

/// Whether the film/world background is rendered transparent (Blender's render.film_transparent).
enum class render_film_transparency {
    /// Leave the scene's own film-transparent setting untouched (legacy behaviour).
    Default,
    /// Force an opaque background.
    Opaque,
    /// Force a transparent background (combine with RGBA for transparent output).
    Transparent,
};

/// The wire name of a render_film_transparency value.
inline std::string_view to_string(render_film_transparency value) noexcept {
    switch (value) {
        case render_film_transparency::Default: return "Default";
        case render_film_transparency::Opaque: return "Opaque";
        case render_film_transparency::Transparent: return "Transparent";
    }
    return "";
}

/// Parses the wire name of a render_film_transparency value; false when the name is unknown.
inline bool try_parse(std::string_view text, render_film_transparency& value) noexcept {
    if (text == "Default") { value = render_film_transparency::Default; return true; }
    if (text == "Opaque") { value = render_film_transparency::Opaque; return true; }
    if (text == "Transparent") { value = render_film_transparency::Transparent; return true; }
    return false;
}

/// Output image format for rendering. APPEND-ONLY: values travel as MemoryPack ints — never reorder or remove members.
enum class render_format {
    PNG,
    EXR,
    JPEG,
    TIFF,
    WEBP,
};

/// The wire name of a render_format value.
inline std::string_view to_string(render_format value) noexcept {
    switch (value) {
        case render_format::PNG: return "PNG";
        case render_format::EXR: return "EXR";
        case render_format::JPEG: return "JPEG";
        case render_format::TIFF: return "TIFF";
        case render_format::WEBP: return "WEBP";
    }
    return "";
}

/// Parses the wire name of a render_format value; false when the name is unknown.
inline bool try_parse(std::string_view text, render_format& value) noexcept {
    if (text == "PNG") { value = render_format::PNG; return true; }
    if (text == "EXR") { value = render_format::EXR; return true; }
    if (text == "JPEG") { value = render_format::JPEG; return true; }
    if (text == "TIFF") { value = render_format::TIFF; return true; }
    if (text == "WEBP") { value = render_format::WEBP; return true; }
    return false;
}

/// Stitching mode for tiled still rendering.
enum class tile_blend_mode {
    /// Crop each rendered tile back to its logical core area before overlay.
    CenterPriorityCrop,
    /// Blend overlap regions with linear feathering and normalized weight accumulation.
    AlphaBlend,
};

/// The wire name of a tile_blend_mode value.
inline std::string_view to_string(tile_blend_mode value) noexcept {
    switch (value) {
        case tile_blend_mode::CenterPriorityCrop: return "CenterPriorityCrop";
        case tile_blend_mode::AlphaBlend: return "AlphaBlend";
    }
    return "";
}

/// Parses the wire name of a tile_blend_mode value; false when the name is unknown.
inline bool try_parse(std::string_view text, tile_blend_mode& value) noexcept {
    if (text == "CenterPriorityCrop") { value = tile_blend_mode::CenterPriorityCrop; return true; }
    if (text == "AlphaBlend") { value = tile_blend_mode::AlphaBlend; return true; }
    return false;
}

/// Video container + codec PRESET for the RenderVideo path. A single preset enum (instead of two independent container/codec axes) keeps invalid combinations unrepresentable on the wire. Default = the legacy behaviour (MP4/H.264), so payloads from older clients that do not send the field are encoded exactly as before. APPEND-ONLY: values travel as MemoryPack ints — never reorder or remove members.
enum class video_format {
    Default,
    Mp4H264,
    Mp4H265,
    WebMVp9,
    /// QuickTime ProRes 422 HQ — the editing/grading intermediate standard. Quality is fixed by the ProRes profile; ConstantRateFactor is ignored.
    MovProres422Hq,
    /// QuickTime ProRes 4444 — carries an ALPHA channel (transparent video for overlays) when the rendered frames have one (RGBA + transparent film). CRF is ignored.
    MovProres4444,
};

/// The wire name of a video_format value.
inline std::string_view to_string(video_format value) noexcept {
    switch (value) {
        case video_format::Default: return "Default";
        case video_format::Mp4H264: return "Mp4H264";
        case video_format::Mp4H265: return "Mp4H265";
        case video_format::WebMVp9: return "WebMVp9";
        case video_format::MovProres422Hq: return "MovProres422Hq";
        case video_format::MovProres4444: return "MovProres4444";
    }
    return "";
}

/// Parses the wire name of a video_format value; false when the name is unknown.
inline bool try_parse(std::string_view text, video_format& value) noexcept {
    if (text == "Default") { value = video_format::Default; return true; }
    if (text == "Mp4H264") { value = video_format::Mp4H264; return true; }
    if (text == "Mp4H265") { value = video_format::Mp4H265; return true; }
    if (text == "WebMVp9") { value = video_format::WebMVp9; return true; }
    if (text == "MovProres422Hq") { value = video_format::MovProres422Hq; return true; }
    if (text == "MovProres4444") { value = video_format::MovProres4444; return true; }
    return false;
}

/// Options for a host-delegated simulation bake (Render.BakeSimulation). The bake runs once on a single node selected by Grid.Delegate (the fastest compatible node, by the same render-throughput benchmark used for distribution), converting an unbaked sequential simulation into a per-frame, frame-addressable OpenVDB cache that is then sliced and rendered distributed.
/// Document type render.bakeOptions@1.
struct render_bake_options {
    static constexpr std::string_view type_id = "render.bakeOptions@1";

    /// Comma-separated simulation kinds to bake. v1 honours "Fluid" (Mantaflow gas/liquid domains). Other kinds (Cloth, Particles, …) reuse the same delegate-bake framework in later iterations.
    std::optional<std::string> simulation_kinds;
    /// Cache format for the baked sequence. v1 produces "OpenVDB" (per-frame, frame-addressable).
    std::optional<std::string> cache_format;
    /// Optional override for the fluid domain resolution (resolution_max). 0 keeps the scene's value. Lets a submitter cap network bake cost / cache size without editing the scene.
    std::optional<int32_t> resolution_max;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (simulation_kinds) {
            w.key("simulationKinds");
            w.value((*simulation_kinds));
        }
        if (cache_format) {
            w.key("cacheFormat");
            w.value((*cache_format));
        }
        if (resolution_max) {
            w.key("resolutionMax");
            w.value((*resolution_max));
        }
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"render.bakeOptions@1\",\"value\":") + to_json() + "}";
    }
};

/// Rendering parameters: format, engine, and quality settings. Shared between SDK, controller, and plugins.
/// Document type render.options@1.
struct render_options {
    static constexpr std::string_view type_id = "render.options@1";

    /// Output image format.
    std::optional<render_format> format;
    /// Render engine.
    std::optional<render_engine> engine;
    /// Sample count. 0 = use scene default.
    std::optional<int32_t> samples;
    /// Output width. 0 = use scene default.
    std::optional<int32_t> resolution_x;
    /// Output height. 0 = use scene default.
    std::optional<int32_t> resolution_y;
    /// Apply denoising to the rendered image.
    std::optional<bool> denoise;
    /// Persistent-batch chunk size: how many frames/tiles Render.SplitBatched groups into one chunk (each chunk renders in a single Blender process). 0 = use the per-engine default (Render.Split derives it from Engine). Declared last so the wire format stays backward compatible — callers (plugin/SDK) that don't set it deserialize to 0 and get the default.
    std::optional<int32_t> batch_size;
    /// Output colour channels. Default reproduces legacy behaviour (RGB for PNG/JPEG, scene default for EXR). Declared after BatchSize so the wire format stays backward compatible — old callers deserialize to Default and render as before.
    std::optional<render_color_mode> color_mode;
    /// Whether the film/world background is rendered transparent. Default leaves the scene's own setting untouched. Appended for wire back-compat.
    std::optional<render_film_transparency> film_transparent;
    /// Output bit depth. Default leaves the scene/format default untouched. Appended for wire back-compat.
    std::optional<render_color_depth> color_depth;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (format) {
            w.key("format");
            w.value(to_string((*format)));
        }
        if (engine) {
            w.key("engine");
            w.value(to_string((*engine)));
        }
        if (samples) {
            w.key("samples");
            w.value((*samples));
        }
        if (resolution_x) {
            w.key("resolutionX");
            w.value((*resolution_x));
        }
        if (resolution_y) {
            w.key("resolutionY");
            w.value((*resolution_y));
        }
        if (denoise) {
            w.key("denoise");
            w.value((*denoise));
        }
        if (batch_size) {
            w.key("batchSize");
            w.value((*batch_size));
        }
        if (color_mode) {
            w.key("colorMode");
            w.value(to_string((*color_mode)));
        }
        if (film_transparent) {
            w.key("filmTransparent");
            w.value(to_string((*film_transparent)));
        }
        if (color_depth) {
            w.key("colorDepth");
            w.value(to_string((*color_depth)));
        }
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"render.options@1\",\"value\":") + to_json() + "}";
    }
};

/// Runtime diagnostics for the packaged render controller tools available on the current node.
/// Document type render.runtimeDiagnostics@1.
struct render_runtime_diagnostics {
    static constexpr std::string_view type_id = "render.runtimeDiagnostics@1";

    /// Runtime target resolved for the current process, such as windows-x64.
    std::optional<std::string> runtime_target;
    /// Whether the packaged Blender runtime is available.
    std::optional<bool> blender_available;
    /// Blender version string when available.
    std::optional<std::string> blender_version;
    /// Render backends detected as available for automatic local selection.
    std::vector<std::string> available_render_backends;
    /// Backend currently selected by the node for automatic rendering.
    std::optional<std::string> selected_render_backend;
    /// Whether automatic local selection resolved to a GPU backend.
    std::optional<bool> uses_gpu_for_rendering;
    /// Human-readable automatic backend selection summary.
    std::optional<std::string> render_backend_selection_message;
    /// Whether the packaged ffmpeg runtime is available.
    std::optional<bool> ffmpeg_available;
    /// ffmpeg version string when available.
    std::optional<std::string> ffmpeg_version;
    /// Whether the packaged ffprobe runtime is available.
    std::optional<bool> ffprobe_available;
    /// ffprobe version string when available.
    std::optional<std::string> ffprobe_version;
    /// Whether tiled center-priority crop stitching is supported.
    std::optional<bool> supports_center_priority_crop;
    /// Whether tiled alpha-blend stitching is supported.
    std::optional<bool> supports_alpha_blend;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (runtime_target) {
            w.key("runtimeTarget");
            w.value((*runtime_target));
        }
        if (blender_available) {
            w.key("blenderAvailable");
            w.value((*blender_available));
        }
        if (blender_version) {
            w.key("blenderVersion");
            w.value((*blender_version));
        }
        w.key("availableRenderBackends");
        w.begin_array();
        for (const auto& item0 : available_render_backends) {
            w.value(item0);
        }
        w.end_array();
        if (selected_render_backend) {
            w.key("selectedRenderBackend");
            w.value((*selected_render_backend));
        }
        if (uses_gpu_for_rendering) {
            w.key("usesGpuForRendering");
            w.value((*uses_gpu_for_rendering));
        }
        if (render_backend_selection_message) {
            w.key("renderBackendSelectionMessage");
            w.value((*render_backend_selection_message));
        }
        if (ffmpeg_available) {
            w.key("ffmpegAvailable");
            w.value((*ffmpeg_available));
        }
        if (ffmpeg_version) {
            w.key("ffmpegVersion");
            w.value((*ffmpeg_version));
        }
        if (ffprobe_available) {
            w.key("ffprobeAvailable");
            w.value((*ffprobe_available));
        }
        if (ffprobe_version) {
            w.key("ffprobeVersion");
            w.value((*ffprobe_version));
        }
        if (supports_center_priority_crop) {
            w.key("supportsCenterPriorityCrop");
            w.value((*supports_center_priority_crop));
        }
        if (supports_alpha_blend) {
            w.key("supportsAlphaBlend");
            w.value((*supports_alpha_blend));
        }
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"render.runtimeDiagnostics@1\",\"value\":") + to_json() + "}";
    }
};

/// Preflight validation result for frame-based rendering on the current packaged runtime.
/// Document type render.preflightFrames@1.
struct render_preflight_frames {
    static constexpr std::string_view type_id = "render.preflightFrames@1";

    /// Whether the current packaged runtime can execute the requested frame render.
    std::optional<bool> can_render;
    /// Runtime target resolved for the current process, such as windows-x64.
    std::optional<std::string> runtime_target;
    /// Human-readable preflight issues that block the requested frame render.
    std::vector<std::string> issues;
    /// Human-readable preflight warnings that do not block the requested frame render.
    std::vector<std::string> warnings;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (can_render) {
            w.key("canRender");
            w.value((*can_render));
        }
        if (runtime_target) {
            w.key("runtimeTarget");
            w.value((*runtime_target));
        }
        w.key("issues");
        w.begin_array();
        for (const auto& item0 : issues) {
            w.value(item0);
        }
        w.end_array();
        w.key("warnings");
        w.begin_array();
        for (const auto& item0 : warnings) {
            w.value(item0);
        }
        w.end_array();
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"render.preflightFrames@1\",\"value\":") + to_json() + "}";
    }
};

/// Preflight validation result for tiled still rendering on the current packaged runtime.
/// Document type render.preflightStillTiled@1.
struct render_preflight_still_tiled {
    static constexpr std::string_view type_id = "render.preflightStillTiled@1";

    /// Whether the current packaged runtime can execute the requested tiled still render.
    std::optional<bool> can_render;
    /// Runtime target resolved for the current process, such as windows-x64.
    std::optional<std::string> runtime_target;
    /// Requested tile blend mode for the preflight validation.
    std::optional<tile_blend_mode> requested_blend_mode;
    /// Human-readable preflight issues that block the requested tiled render.
    std::vector<std::string> issues;
    /// Human-readable preflight warnings that do not block the requested tiled render.
    std::vector<std::string> warnings;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (can_render) {
            w.key("canRender");
            w.value((*can_render));
        }
        if (runtime_target) {
            w.key("runtimeTarget");
            w.value((*runtime_target));
        }
        if (requested_blend_mode) {
            w.key("requestedBlendMode");
            w.value(to_string((*requested_blend_mode)));
        }
        w.key("issues");
        w.begin_array();
        for (const auto& item0 : issues) {
            w.value(item0);
        }
        w.end_array();
        w.key("warnings");
        w.begin_array();
        for (const auto& item0 : warnings) {
            w.value(item0);
        }
        w.end_array();
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"render.preflightStillTiled@1\",\"value\":") + to_json() + "}";
    }
};

/// Preflight validation result for video rendering on the current packaged runtime.
/// Document type render.preflightVideo@1.
struct render_preflight_video {
    static constexpr std::string_view type_id = "render.preflightVideo@1";

    /// Whether the current packaged runtime can execute the requested video render.
    std::optional<bool> can_render;
    /// Runtime target resolved for the current process, such as windows-x64.
    std::optional<std::string> runtime_target;
    /// Human-readable preflight issues that block the requested video render.
    std::vector<std::string> issues;
    /// Human-readable preflight warnings that do not block the requested video render.
    std::vector<std::string> warnings;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (can_render) {
            w.key("canRender");
            w.value((*can_render));
        }
        if (runtime_target) {
            w.key("runtimeTarget");
            w.value((*runtime_target));
        }
        w.key("issues");
        w.begin_array();
        for (const auto& item0 : issues) {
            w.value(item0);
        }
        w.end_array();
        w.key("warnings");
        w.begin_array();
        for (const auto& item0 : warnings) {
            w.value(item0);
        }
        w.end_array();
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"render.preflightVideo@1\",\"value\":") + to_json() + "}";
    }
};

/// Unified preflight validation result across the currently supported render modes.
/// Document type render.preflight@1.
struct render_preflight {
    static constexpr std::string_view type_id = "render.preflight@1";

    /// Packaged runtime diagnostics used to evaluate the preflight request.
    std::optional<render_runtime_diagnostics> runtime_diagnostics;
    /// Single-frame still preflight result, evaluated as a one-frame specialization of frame rendering.
    std::optional<render_preflight_frames> still;
    /// Frame-range render preflight result.
    std::optional<render_preflight_frames> frames;
    /// Tiled-still render preflight result.
    std::optional<render_preflight_still_tiled> still_tiled;
    /// Video render preflight result.
    std::optional<render_preflight_video> video;
    /// Whether all currently evaluated render modes are ready on the current packaged runtime.
    std::optional<bool> can_render_all;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (runtime_diagnostics) {
            w.key("runtimeDiagnostics");
            (*runtime_diagnostics).write_json(w);
        }
        if (still) {
            w.key("still");
            (*still).write_json(w);
        }
        if (frames) {
            w.key("frames");
            (*frames).write_json(w);
        }
        if (still_tiled) {
            w.key("stillTiled");
            (*still_tiled).write_json(w);
        }
        if (video) {
            w.key("video");
            (*video).write_json(w);
        }
        if (can_render_all) {
            w.key("canRenderAll");
            w.value((*can_render_all));
        }
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"render.preflight@1\",\"value\":") + to_json() + "}";
    }
};

/// Metadata about one addon-side dependency artifact associated with a scene reference.
/// Document type render.sceneAttachmentRef@1.
struct render_scene_attachment_ref {
    static constexpr std::string_view type_id = "render.sceneAttachmentRef@1";

    /// Logical dependency kind, for example ImageAsset or Font.
    std::optional<std::string> kind;
    /// Cloud blob identifier of the uploaded dependency artifact when it is transferred separately from the blend file.
    std::optional<std::string> blob_id;
    /// Original addon-side source path observed in the Blender scene.
    std::optional<std::string> original_path;
    /// Logical relative path or slot name inside the addon-side scene package.
    std::optional<std::string> relative_path;
    /// Packaging strategy attempted by the addon for this dependency.
    std::optional<std::string> packaging_strategy;
    /// Frame this artifact belongs to, for per-frame baked simulation caches (one cache file per frame). null = applies to all frames (textures, linked libraries, and other non-frame-specific deps). Lets Render.Split* send each render node only the cache files for the frames it renders. Appended last for MemoryPack wire back-compatibility.
    std::optional<int32_t> frame;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (kind) {
            w.key("kind");
            w.value((*kind));
        }
        if (blob_id) {
            w.key("blobId");
            w.value((*blob_id));
        }
        if (original_path) {
            w.key("originalPath");
            w.value((*original_path));
        }
        if (relative_path) {
            w.key("relativePath");
            w.value((*relative_path));
        }
        if (packaging_strategy) {
            w.key("packagingStrategy");
            w.value((*packaging_strategy));
        }
        if (frame) {
            w.key("frame");
            w.value((*frame));
        }
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"render.sceneAttachmentRef@1\",\"value\":") + to_json() + "}";
    }
};

/// Bootstrap blob-backed typed-scene reference for host-side BuildBlendFromRefs execution. Current implementation points directly at a prepared .blend blob in storage.
/// Document type render.sceneRef@1.
struct render_scene_ref {
    static constexpr std::string_view type_id = "render.sceneRef@1";

    /// Blob identifier of a prepared .blend payload.
    std::optional<std::string> blend_blob_id;
    /// Addon-side metadata about dependency artifacts associated with the referenced scene payload.
    std::vector<render_scene_attachment_ref> attached_files;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (blend_blob_id) {
            w.key("blendBlobId");
            w.value((*blend_blob_id));
        }
        w.key("attachedFiles");
        w.begin_array();
        for (const auto& item0 : attached_files) {
            item0.write_json(w);
        }
        w.end_array();
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"render.sceneRef@1\",\"value\":") + to_json() + "}";
    }
};

/// Tile-specific options for tiled still rendering. Kept separate from RenderOptionsData because different scripts may need different tiling inputs.
/// Document type render.tileOptions@1.
struct render_tile_options {
    static constexpr std::string_view type_id = "render.tileOptions@1";

    /// Tile overlap in pixels. Current tiled slice uses center-priority crop when overlap is greater than zero.
    std::optional<int32_t> overlap_px;
    /// Stitching strategy for overlap regions.
    std::optional<tile_blend_mode> blend_mode;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (overlap_px) {
            w.key("overlapPx");
            w.value((*overlap_px));
        }
        if (blend_mode) {
            w.key("blendMode");
            w.value(to_string((*blend_mode)));
        }
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"render.tileOptions@1\",\"value\":") + to_json() + "}";
    }
};

/// Validation result for one uploaded .blend scene.
/// Document type render.validateBlend@1.
struct render_validate_blend {
    static constexpr std::string_view type_id = "render.validateBlend@1";

    /// Whether the scene is currently considered portable and valid for the supported remote render flow.
    std::optional<bool> is_valid;
    /// Validation issues that block the current remote render flow.
    std::vector<std::string> issues;
    /// Validation findings that do not currently block the remote render flow but may require user attention.
    std::vector<std::string> warnings;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (is_valid) {
            w.key("isValid");
            w.value((*is_valid));
        }
        w.key("issues");
        w.begin_array();
        for (const auto& item0 : issues) {
            w.value(item0);
        }
        w.end_array();
        w.key("warnings");
        w.begin_array();
        for (const auto& item0 : warnings) {
            w.value(item0);
        }
        w.end_array();
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"render.validateBlend@1\",\"value\":") + to_json() + "}";
    }
};

/// Video encoding options for the first production RenderVideo path. Current scope is intentionally minimal: MP4 container with H.264 video and no audio.
/// Document type render.videoOptions@1.
struct render_video_options {
    static constexpr std::string_view type_id = "render.videoOptions@1";

    /// Output frame rate in frames per second.
    std::optional<int32_t> frame_rate;
    /// CRF quality setting passed to the ffmpeg encoder (libx264/libx265/libvpx-vp9). Lower values mean higher quality and larger output.
    std::optional<int32_t> constant_rate_factor;
    /// Container + codec preset. APPENDED after ConstantRateFactor (wire order is append-only); Default keeps the legacy MP4/H.264 behaviour for old payloads.
    std::optional<video_format> format;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (frame_rate) {
            w.key("frameRate");
            w.value((*frame_rate));
        }
        if (constant_rate_factor) {
            w.key("constantRateFactor");
            w.value((*constant_rate_factor));
        }
        if (format) {
            w.key("format");
            w.value(to_string((*format)));
        }
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"render.videoOptions@1\",\"value\":") + to_json() + "}";
    }
};

/// Every published type id of the component.
inline constexpr std::string_view type_ids[] = {
    "render.bakeOptions@1",
    "render.options@1",
    "render.preflight@1",
    "render.preflightFrames@1",
    "render.preflightStillTiled@1",
    "render.preflightVideo@1",
    "render.runtimeDiagnostics@1",
    "render.sceneAttachmentRef@1",
    "render.sceneRef@1",
    "render.tileOptions@1",
    "render.validateBlend@1",
    "render.videoOptions@1",
};

} // namespace omnibuscloud::documents::render

#endif // OMNIBUSCLOUD_DOCUMENTS_RENDER_HPP
