# Generated by OutWit.Cloud.Documents.Generator 1.0.0 from OutWit.Controller.Render.Model 1.8.0.
# Do not edit: regenerate from the model assembly.
#
# OmnibusCloud job document vocabulary: render
#
# Every dataclass below is a published document type. Build one, then
# to_parameter() gives the job request parameter ({"kind": "document", ...})
# to place into the request's positional parameter list; from_json() reads
# a value document's "value" back into the typed object. Wire convention:
# camelCase keys, enum member names as strings, None properties omitted.
# Optional fields left as None are omitted, which lets the server apply its
# own defaults; a field the server marks required has no default here.
#
# Standard library only, Python 3.10+ (keyword-only dataclasses); no OmnibusCloud
# SDK import is needed to use it.
from __future__ import annotations

import datetime as _datetime
import enum as _enum
import re as _re
import uuid as _uuid
from dataclasses import dataclass as _dataclass
from dataclasses import field as _field
from typing import Any as _Any
from typing import ClassVar as _ClassVar
from typing import Optional as _Optional

COMPONENT = "render"
"""The component whose vocabulary this module binds."""

TYPE_IDS = (
    "render.bakeOptions@1",
    "render.options@1",
    "render.preflight@1",
    "render.preflightFrames@1",
    "render.preflightStillTiled@1",
    "render.preflightVideo@1",
    "render.runtimeDiagnostics@1",
    "render.sceneAttachmentRef@1",
    "render.sceneRef@1",
    "render.tileOptions@1",
    "render.validateBlend@1",
    "render.videoOptions@1",
)
"""Every published type id of the component."""


_FRACTION = _re.compile(r"(\.\d{6})\d+")


def _omit_none(values: dict) -> dict:
    return {key: value for key, value in values.items() if value is not None}


def _enum_to_json(value: _Any) -> _Any:
    return value.value if isinstance(value, _enum.Enum) else value


def _enum_from_json(enum_type: type, value: _Any) -> _Any:
    # A member name this binding does not know (newer server) is kept as text.
    try:
        return enum_type(value)
    except ValueError:
        return value


def _uuid_to_json(value: _Any) -> str:
    return str(value)


def _uuid_from_json(value: _Any) -> _uuid.UUID:
    return value if isinstance(value, _uuid.UUID) else _uuid.UUID(str(value))


def _datetime_to_json(value: _Any) -> str:
    # The server's form: ISO 8601, fraction only when non-zero and without
    # trailing zeros, 'Z' for UTC, offset otherwise, nothing for naive values.
    if isinstance(value, str):
        return value
    text = value.strftime("%Y-%m-%dT%H:%M:%S")
    if value.microsecond:
        text += "." + f"{value.microsecond:06d}".rstrip("0")
    offset = value.utcoffset()
    if offset is None:
        return text
    if offset == _datetime.timedelta(0):
        return text + "Z"
    total = int(offset.total_seconds())
    sign = "+" if total >= 0 else "-"
    total = abs(total)
    return text + f"{sign}{total // 3600:02d}:{(total % 3600) // 60:02d}"


def _datetime_from_json(value: _Any) -> _datetime.datetime:
    if isinstance(value, _datetime.datetime):
        return value
    text = str(value)
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    # .NET writes seven fractional digits; Python parses at most six.
    return _datetime.datetime.fromisoformat(_FRACTION.sub(r"\1", text))


class RenderColorDepth(str, _enum.Enum):
    """Output bit depth per channel (Blender's image_settings.color_depth)."""

    #: Leave the scene/format default untouched (legacy behaviour).
    Default = "Default"
    #: 8-bit (PNG/JPEG).
    Eight = "Eight"
    #: 16-bit (PNG, EXR half).
    Sixteen = "Sixteen"
    #: 32-bit (EXR full float).
    ThirtyTwo = "ThirtyTwo"


class RenderColorMode(str, _enum.Enum):
    """Output colour channels for a render."""

    #: Legacy behaviour: force RGB for PNG/JPEG, leave the scene default for EXR. Keeps old clients (which don't send a colour mode) rendering exactly as before.
    Default = "Default"
    #: RGB (no alpha).
    RGB = "RGB"
    #: RGBA (with alpha) — needed for transparent renders / compositing.
    RGBA = "RGBA"


class RenderEngine(str, _enum.Enum):
    """Render engine selection."""

    Cycles = "Cycles"
    Eevee = "Eevee"
    GreasePencil = "GreasePencil"


class RenderFilmTransparency(str, _enum.Enum):
    """Whether the film/world background is rendered transparent (Blender's render.film_transparent)."""

    #: Leave the scene's own film-transparent setting untouched (legacy behaviour).
    Default = "Default"
    #: Force an opaque background.
    Opaque = "Opaque"
    #: Force a transparent background (combine with RGBA for transparent output).
    Transparent = "Transparent"


class RenderFormat(str, _enum.Enum):
    """Output image format for rendering. APPEND-ONLY: values travel as MemoryPack ints — never reorder or remove members."""

    PNG = "PNG"
    EXR = "EXR"
    JPEG = "JPEG"
    TIFF = "TIFF"
    WEBP = "WEBP"


class TileBlendMode(str, _enum.Enum):
    """Stitching mode for tiled still rendering."""

    #: Crop each rendered tile back to its logical core area before overlay.
    CenterPriorityCrop = "CenterPriorityCrop"
    #: Blend overlap regions with linear feathering and normalized weight accumulation.
    AlphaBlend = "AlphaBlend"


class VideoFormat(str, _enum.Enum):
    """Video container + codec PRESET for the RenderVideo path. A single preset enum (instead of two independent container/codec axes) keeps invalid combinations unrepresentable on the wire. Default = the legacy behaviour (MP4/H.264), so payloads from older clients that do not send the field are encoded exactly as before. APPEND-ONLY: values travel as MemoryPack ints — never reorder or remove members."""

    Default = "Default"
    Mp4H264 = "Mp4H264"
    Mp4H265 = "Mp4H265"
    WebMVp9 = "WebMVp9"
    #: QuickTime ProRes 422 HQ — the editing/grading intermediate standard. Quality is fixed by the ProRes profile; ConstantRateFactor is ignored.
    MovProres422Hq = "MovProres422Hq"
    #: QuickTime ProRes 4444 — carries an ALPHA channel (transparent video for overlays) when the rendered frames have one (RGBA + transparent film). CRF is ignored.
    MovProres4444 = "MovProres4444"


@_dataclass(kw_only=True)
class RenderBakeOptions:
    """Options for a host-delegated simulation bake (Render.BakeSimulation). The bake runs once on a single node selected by Grid.Delegate (the fastest compatible node, by the same render-throughput benchmark used for distribution), converting an unbaked sequential simulation into a per-frame, frame-addressable OpenVDB cache that is then sliced and rendered distributed."""

    TYPE_ID: _ClassVar[str] = "render.bakeOptions@1"
    """The published type id this class binds."""

    #: Comma-separated simulation kinds to bake. v1 honours "Fluid" (Mantaflow gas/liquid domains). Other kinds (Cloth, Particles, …) reuse the same delegate-bake framework in later iterations.
    simulation_kinds: _Optional[str] = None
    #: Cache format for the baked sequence. v1 produces "OpenVDB" (per-frame, frame-addressable).
    cache_format: _Optional[str] = None
    #: Optional override for the fluid domain resolution (resolution_max). 0 keeps the scene's value. Lets a submitter cap network bake cost / cache size without editing the scene.
    resolution_max: _Optional[int] = None

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "simulationKinds": self.simulation_kinds,
            "cacheFormat": self.cache_format,
            "resolutionMax": self.resolution_max,
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "RenderBakeOptions":
        """Reads the wire object of a value document."""
        return cls(
            simulation_kinds=data.get("simulationKinds"),
            cache_format=data.get("cacheFormat"),
            resolution_max=data.get("resolutionMax"),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class RenderOptions:
    """Rendering parameters: format, engine, and quality settings. Shared between SDK, controller, and plugins."""

    TYPE_ID: _ClassVar[str] = "render.options@1"
    """The published type id this class binds."""

    #: Output image format.
    format: _Optional[RenderFormat] = None
    #: Render engine.
    engine: _Optional[RenderEngine] = None
    #: Sample count. 0 = use scene default.
    samples: _Optional[int] = None
    #: Output width. 0 = use scene default.
    resolution_x: _Optional[int] = None
    #: Output height. 0 = use scene default.
    resolution_y: _Optional[int] = None
    #: Apply denoising to the rendered image.
    denoise: _Optional[bool] = None
    #: Persistent-batch chunk size: how many frames/tiles Render.SplitBatched groups into one chunk (each chunk renders in a single Blender process). 0 = use the per-engine default (Render.Split derives it from Engine). Declared last so the wire format stays backward compatible — callers (plugin/SDK) that don't set it deserialize to 0 and get the default.
    batch_size: _Optional[int] = None
    #: Output colour channels. Default reproduces legacy behaviour (RGB for PNG/JPEG, scene default for EXR). Declared after BatchSize so the wire format stays backward compatible — old callers deserialize to Default and render as before.
    color_mode: _Optional[RenderColorMode] = None
    #: Whether the film/world background is rendered transparent. Default leaves the scene's own setting untouched. Appended for wire back-compat.
    film_transparent: _Optional[RenderFilmTransparency] = None
    #: Output bit depth. Default leaves the scene/format default untouched. Appended for wire back-compat.
    color_depth: _Optional[RenderColorDepth] = None

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "format": (None if self.format is None else _enum_to_json(self.format)),
            "engine": (None if self.engine is None else _enum_to_json(self.engine)),
            "samples": self.samples,
            "resolutionX": self.resolution_x,
            "resolutionY": self.resolution_y,
            "denoise": self.denoise,
            "batchSize": self.batch_size,
            "colorMode": (None if self.color_mode is None else _enum_to_json(self.color_mode)),
            "filmTransparent": (None if self.film_transparent is None else _enum_to_json(self.film_transparent)),
            "colorDepth": (None if self.color_depth is None else _enum_to_json(self.color_depth)),
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "RenderOptions":
        """Reads the wire object of a value document."""
        return cls(
            format=(None if data.get("format") is None else _enum_from_json(RenderFormat, data.get("format"))),
            engine=(None if data.get("engine") is None else _enum_from_json(RenderEngine, data.get("engine"))),
            samples=data.get("samples"),
            resolution_x=data.get("resolutionX"),
            resolution_y=data.get("resolutionY"),
            denoise=data.get("denoise"),
            batch_size=data.get("batchSize"),
            color_mode=(None if data.get("colorMode") is None else _enum_from_json(RenderColorMode, data.get("colorMode"))),
            film_transparent=(None if data.get("filmTransparent") is None else _enum_from_json(RenderFilmTransparency, data.get("filmTransparent"))),
            color_depth=(None if data.get("colorDepth") is None else _enum_from_json(RenderColorDepth, data.get("colorDepth"))),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class RenderRuntimeDiagnostics:
    """Runtime diagnostics for the packaged render controller tools available on the current node."""

    TYPE_ID: _ClassVar[str] = "render.runtimeDiagnostics@1"
    """The published type id this class binds."""

    #: Runtime target resolved for the current process, such as windows-x64.
    runtime_target: _Optional[str] = None
    #: Whether the packaged Blender runtime is available.
    blender_available: _Optional[bool] = None
    #: Blender version string when available.
    blender_version: _Optional[str] = None
    #: Render backends detected as available for automatic local selection.
    available_render_backends: list[str] = _field(default_factory=list)
    #: Backend currently selected by the node for automatic rendering.
    selected_render_backend: _Optional[str] = None
    #: Whether automatic local selection resolved to a GPU backend.
    uses_gpu_for_rendering: _Optional[bool] = None
    #: Human-readable automatic backend selection summary.
    render_backend_selection_message: _Optional[str] = None
    #: Whether the packaged ffmpeg runtime is available.
    ffmpeg_available: _Optional[bool] = None
    #: ffmpeg version string when available.
    ffmpeg_version: _Optional[str] = None
    #: Whether the packaged ffprobe runtime is available.
    ffprobe_available: _Optional[bool] = None
    #: ffprobe version string when available.
    ffprobe_version: _Optional[str] = None
    #: Whether tiled center-priority crop stitching is supported.
    supports_center_priority_crop: _Optional[bool] = None
    #: Whether tiled alpha-blend stitching is supported.
    supports_alpha_blend: _Optional[bool] = None

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "runtimeTarget": self.runtime_target,
            "blenderAvailable": self.blender_available,
            "blenderVersion": self.blender_version,
            "availableRenderBackends": (None if self.available_render_backends is None else list(self.available_render_backends)),
            "selectedRenderBackend": self.selected_render_backend,
            "usesGpuForRendering": self.uses_gpu_for_rendering,
            "renderBackendSelectionMessage": self.render_backend_selection_message,
            "ffmpegAvailable": self.ffmpeg_available,
            "ffmpegVersion": self.ffmpeg_version,
            "ffprobeAvailable": self.ffprobe_available,
            "ffprobeVersion": self.ffprobe_version,
            "supportsCenterPriorityCrop": self.supports_center_priority_crop,
            "supportsAlphaBlend": self.supports_alpha_blend,
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "RenderRuntimeDiagnostics":
        """Reads the wire object of a value document."""
        return cls(
            runtime_target=data.get("runtimeTarget"),
            blender_available=data.get("blenderAvailable"),
            blender_version=data.get("blenderVersion"),
            available_render_backends=([] if data.get("availableRenderBackends") is None else list(data.get("availableRenderBackends"))),
            selected_render_backend=data.get("selectedRenderBackend"),
            uses_gpu_for_rendering=data.get("usesGpuForRendering"),
            render_backend_selection_message=data.get("renderBackendSelectionMessage"),
            ffmpeg_available=data.get("ffmpegAvailable"),
            ffmpeg_version=data.get("ffmpegVersion"),
            ffprobe_available=data.get("ffprobeAvailable"),
            ffprobe_version=data.get("ffprobeVersion"),
            supports_center_priority_crop=data.get("supportsCenterPriorityCrop"),
            supports_alpha_blend=data.get("supportsAlphaBlend"),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class RenderPreflightFrames:
    """Preflight validation result for frame-based rendering on the current packaged runtime."""

    TYPE_ID: _ClassVar[str] = "render.preflightFrames@1"
    """The published type id this class binds."""

    #: Whether the current packaged runtime can execute the requested frame render.
    can_render: _Optional[bool] = None
    #: Runtime target resolved for the current process, such as windows-x64.
    runtime_target: _Optional[str] = None
    #: Human-readable preflight issues that block the requested frame render.
    issues: list[str] = _field(default_factory=list)
    #: Human-readable preflight warnings that do not block the requested frame render.
    warnings: list[str] = _field(default_factory=list)

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "canRender": self.can_render,
            "runtimeTarget": self.runtime_target,
            "issues": (None if self.issues is None else list(self.issues)),
            "warnings": (None if self.warnings is None else list(self.warnings)),
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "RenderPreflightFrames":
        """Reads the wire object of a value document."""
        return cls(
            can_render=data.get("canRender"),
            runtime_target=data.get("runtimeTarget"),
            issues=([] if data.get("issues") is None else list(data.get("issues"))),
            warnings=([] if data.get("warnings") is None else list(data.get("warnings"))),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class RenderPreflightStillTiled:
    """Preflight validation result for tiled still rendering on the current packaged runtime."""

    TYPE_ID: _ClassVar[str] = "render.preflightStillTiled@1"
    """The published type id this class binds."""

    #: Whether the current packaged runtime can execute the requested tiled still render.
    can_render: _Optional[bool] = None
    #: Runtime target resolved for the current process, such as windows-x64.
    runtime_target: _Optional[str] = None
    #: Requested tile blend mode for the preflight validation.
    requested_blend_mode: _Optional[TileBlendMode] = None
    #: Human-readable preflight issues that block the requested tiled render.
    issues: list[str] = _field(default_factory=list)
    #: Human-readable preflight warnings that do not block the requested tiled render.
    warnings: list[str] = _field(default_factory=list)

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "canRender": self.can_render,
            "runtimeTarget": self.runtime_target,
            "requestedBlendMode": (None if self.requested_blend_mode is None else _enum_to_json(self.requested_blend_mode)),
            "issues": (None if self.issues is None else list(self.issues)),
            "warnings": (None if self.warnings is None else list(self.warnings)),
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "RenderPreflightStillTiled":
        """Reads the wire object of a value document."""
        return cls(
            can_render=data.get("canRender"),
            runtime_target=data.get("runtimeTarget"),
            requested_blend_mode=(None if data.get("requestedBlendMode") is None else _enum_from_json(TileBlendMode, data.get("requestedBlendMode"))),
            issues=([] if data.get("issues") is None else list(data.get("issues"))),
            warnings=([] if data.get("warnings") is None else list(data.get("warnings"))),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class RenderPreflightVideo:
    """Preflight validation result for video rendering on the current packaged runtime."""

    TYPE_ID: _ClassVar[str] = "render.preflightVideo@1"
    """The published type id this class binds."""

    #: Whether the current packaged runtime can execute the requested video render.
    can_render: _Optional[bool] = None
    #: Runtime target resolved for the current process, such as windows-x64.
    runtime_target: _Optional[str] = None
    #: Human-readable preflight issues that block the requested video render.
    issues: list[str] = _field(default_factory=list)
    #: Human-readable preflight warnings that do not block the requested video render.
    warnings: list[str] = _field(default_factory=list)

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "canRender": self.can_render,
            "runtimeTarget": self.runtime_target,
            "issues": (None if self.issues is None else list(self.issues)),
            "warnings": (None if self.warnings is None else list(self.warnings)),
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "RenderPreflightVideo":
        """Reads the wire object of a value document."""
        return cls(
            can_render=data.get("canRender"),
            runtime_target=data.get("runtimeTarget"),
            issues=([] if data.get("issues") is None else list(data.get("issues"))),
            warnings=([] if data.get("warnings") is None else list(data.get("warnings"))),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class RenderPreflight:
    """Unified preflight validation result across the currently supported render modes."""

    TYPE_ID: _ClassVar[str] = "render.preflight@1"
    """The published type id this class binds."""

    #: Packaged runtime diagnostics used to evaluate the preflight request.
    runtime_diagnostics: _Optional[RenderRuntimeDiagnostics] = None
    #: Single-frame still preflight result, evaluated as a one-frame specialization of frame rendering.
    still: _Optional[RenderPreflightFrames] = None
    #: Frame-range render preflight result.
    frames: _Optional[RenderPreflightFrames] = None
    #: Tiled-still render preflight result.
    still_tiled: _Optional[RenderPreflightStillTiled] = None
    #: Video render preflight result.
    video: _Optional[RenderPreflightVideo] = None
    #: Whether all currently evaluated render modes are ready on the current packaged runtime.
    can_render_all: _Optional[bool] = None

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "runtimeDiagnostics": (None if self.runtime_diagnostics is None else self.runtime_diagnostics.to_json()),
            "still": (None if self.still is None else self.still.to_json()),
            "frames": (None if self.frames is None else self.frames.to_json()),
            "stillTiled": (None if self.still_tiled is None else self.still_tiled.to_json()),
            "video": (None if self.video is None else self.video.to_json()),
            "canRenderAll": self.can_render_all,
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "RenderPreflight":
        """Reads the wire object of a value document."""
        return cls(
            runtime_diagnostics=(None if data.get("runtimeDiagnostics") is None else RenderRuntimeDiagnostics.from_json(data.get("runtimeDiagnostics"))),
            still=(None if data.get("still") is None else RenderPreflightFrames.from_json(data.get("still"))),
            frames=(None if data.get("frames") is None else RenderPreflightFrames.from_json(data.get("frames"))),
            still_tiled=(None if data.get("stillTiled") is None else RenderPreflightStillTiled.from_json(data.get("stillTiled"))),
            video=(None if data.get("video") is None else RenderPreflightVideo.from_json(data.get("video"))),
            can_render_all=data.get("canRenderAll"),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class RenderSceneAttachmentRef:
    """Metadata about one addon-side dependency artifact associated with a scene reference."""

    TYPE_ID: _ClassVar[str] = "render.sceneAttachmentRef@1"
    """The published type id this class binds."""

    #: Logical dependency kind, for example ImageAsset or Font.
    kind: _Optional[str] = None
    #: Cloud blob identifier of the uploaded dependency artifact when it is transferred separately from the blend file.
    blob_id: _Optional[_uuid.UUID] = None
    #: Original addon-side source path observed in the Blender scene.
    original_path: _Optional[str] = None
    #: Logical relative path or slot name inside the addon-side scene package.
    relative_path: _Optional[str] = None
    #: Packaging strategy attempted by the addon for this dependency.
    packaging_strategy: _Optional[str] = None
    #: Frame this artifact belongs to, for per-frame baked simulation caches (one cache file per frame). null = applies to all frames (textures, linked libraries, and other non-frame-specific deps). Lets Render.Split* send each render node only the cache files for the frames it renders. Appended last for MemoryPack wire back-compatibility.
    frame: _Optional[int] = None

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "kind": self.kind,
            "blobId": (None if self.blob_id is None else _uuid_to_json(self.blob_id)),
            "originalPath": self.original_path,
            "relativePath": self.relative_path,
            "packagingStrategy": self.packaging_strategy,
            "frame": self.frame,
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "RenderSceneAttachmentRef":
        """Reads the wire object of a value document."""
        return cls(
            kind=data.get("kind"),
            blob_id=(None if data.get("blobId") is None else _uuid_from_json(data.get("blobId"))),
            original_path=data.get("originalPath"),
            relative_path=data.get("relativePath"),
            packaging_strategy=data.get("packagingStrategy"),
            frame=data.get("frame"),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class RenderSceneRef:
    """Bootstrap blob-backed typed-scene reference for host-side BuildBlendFromRefs execution. Current implementation points directly at a prepared .blend blob in storage."""

    TYPE_ID: _ClassVar[str] = "render.sceneRef@1"
    """The published type id this class binds."""

    #: Blob identifier of a prepared .blend payload.
    blend_blob_id: _Optional[_uuid.UUID] = None
    #: Addon-side metadata about dependency artifacts associated with the referenced scene payload.
    attached_files: list[RenderSceneAttachmentRef] = _field(default_factory=list)

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "blendBlobId": (None if self.blend_blob_id is None else _uuid_to_json(self.blend_blob_id)),
            "attachedFiles": (None if self.attached_files is None else [item0.to_json() for item0 in self.attached_files]),
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "RenderSceneRef":
        """Reads the wire object of a value document."""
        return cls(
            blend_blob_id=(None if data.get("blendBlobId") is None else _uuid_from_json(data.get("blendBlobId"))),
            attached_files=([] if data.get("attachedFiles") is None else [(None if item0 is None else RenderSceneAttachmentRef.from_json(item0)) for item0 in data.get("attachedFiles")]),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class RenderTileOptions:
    """Tile-specific options for tiled still rendering. Kept separate from RenderOptionsData because different scripts may need different tiling inputs."""

    TYPE_ID: _ClassVar[str] = "render.tileOptions@1"
    """The published type id this class binds."""

    #: Tile overlap in pixels. Current tiled slice uses center-priority crop when overlap is greater than zero.
    overlap_px: _Optional[int] = None
    #: Stitching strategy for overlap regions.
    blend_mode: _Optional[TileBlendMode] = None

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "overlapPx": self.overlap_px,
            "blendMode": (None if self.blend_mode is None else _enum_to_json(self.blend_mode)),
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "RenderTileOptions":
        """Reads the wire object of a value document."""
        return cls(
            overlap_px=data.get("overlapPx"),
            blend_mode=(None if data.get("blendMode") is None else _enum_from_json(TileBlendMode, data.get("blendMode"))),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class RenderValidateBlend:
    """Validation result for one uploaded .blend scene."""

    TYPE_ID: _ClassVar[str] = "render.validateBlend@1"
    """The published type id this class binds."""

    #: Whether the scene is currently considered portable and valid for the supported remote render flow.
    is_valid: _Optional[bool] = None
    #: Validation issues that block the current remote render flow.
    issues: list[str] = _field(default_factory=list)
    #: Validation findings that do not currently block the remote render flow but may require user attention.
    warnings: list[str] = _field(default_factory=list)

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "isValid": self.is_valid,
            "issues": (None if self.issues is None else list(self.issues)),
            "warnings": (None if self.warnings is None else list(self.warnings)),
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "RenderValidateBlend":
        """Reads the wire object of a value document."""
        return cls(
            is_valid=data.get("isValid"),
            issues=([] if data.get("issues") is None else list(data.get("issues"))),
            warnings=([] if data.get("warnings") is None else list(data.get("warnings"))),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class RenderVideoOptions:
    """Video encoding options for the first production RenderVideo path. Current scope is intentionally minimal: MP4 container with H.264 video and no audio."""

    TYPE_ID: _ClassVar[str] = "render.videoOptions@1"
    """The published type id this class binds."""

    #: Output frame rate in frames per second.
    frame_rate: _Optional[int] = None
    #: CRF quality setting passed to the ffmpeg encoder (libx264/libx265/libvpx-vp9). Lower values mean higher quality and larger output.
    constant_rate_factor: _Optional[int] = None
    #: Container + codec preset. APPENDED after ConstantRateFactor (wire order is append-only); Default keeps the legacy MP4/H.264 behaviour for old payloads.
    format: _Optional[VideoFormat] = None

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "frameRate": self.frame_rate,
            "constantRateFactor": self.constant_rate_factor,
            "format": (None if self.format is None else _enum_to_json(self.format)),
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "RenderVideoOptions":
        """Reads the wire object of a value document."""
        return cls(
            frame_rate=data.get("frameRate"),
            constant_rate_factor=data.get("constantRateFactor"),
            format=(None if data.get("format") is None else _enum_from_json(VideoFormat, data.get("format"))),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


DOCUMENT_TYPES = {
    "render.bakeOptions@1": RenderBakeOptions,
    "render.options@1": RenderOptions,
    "render.preflight@1": RenderPreflight,
    "render.preflightFrames@1": RenderPreflightFrames,
    "render.preflightStillTiled@1": RenderPreflightStillTiled,
    "render.preflightVideo@1": RenderPreflightVideo,
    "render.runtimeDiagnostics@1": RenderRuntimeDiagnostics,
    "render.sceneAttachmentRef@1": RenderSceneAttachmentRef,
    "render.sceneRef@1": RenderSceneRef,
    "render.tileOptions@1": RenderTileOptions,
    "render.validateBlend@1": RenderValidateBlend,
    "render.videoOptions@1": RenderVideoOptions,
}
"""Type id -> dataclass, for reading value documents by their declared type."""


def from_value_document(document: dict[str, _Any]) -> _Any:
    """Reads a value document (schema v1) of a type this module binds; primitives pass through."""
    kind = document.get("kind")
    if kind == "null":
        return None
    if kind != "document":
        return document.get("value")
    type_id = document.get("type")
    binding = DOCUMENT_TYPES.get(type_id)
    if binding is None:
        raise KeyError(f"document type {type_id!r} is not part of the {COMPONENT} vocabulary")
    return binding.from_json(document.get("value") or {})


__all__ = [
    "COMPONENT",
    "TYPE_IDS",
    "DOCUMENT_TYPES",
    "from_value_document",
    "RenderColorDepth",
    "RenderColorMode",
    "RenderEngine",
    "RenderFilmTransparency",
    "RenderFormat",
    "TileBlendMode",
    "VideoFormat",
    "RenderBakeOptions",
    "RenderOptions",
    "RenderPreflight",
    "RenderPreflightFrames",
    "RenderPreflightStillTiled",
    "RenderPreflightVideo",
    "RenderRuntimeDiagnostics",
    "RenderSceneAttachmentRef",
    "RenderSceneRef",
    "RenderTileOptions",
    "RenderValidateBlend",
    "RenderVideoOptions",
]
