Job:GustavsonMultiplyDistributed(MatrixSparse:matrix1, MatrixSparse:matrix2)
{
    Int:rowCount = Matrix.RowCount(matrix1);
    Int:columnCount = Matrix.ColumnCount(matrix2);
    IntCollection:rowIndices = Int.Range(0, rowCount);
    VectorSparseCollection:rows = Matrix.GetRows(matrix1);
    
    TupleCollection:tasks = Zip(rowIndices, rows);
    
    TupleCollection:result = Grid.ForEach(task in tasks) => GustavsonMultiply(task.Item1, task.Item2, matrix2);
    
    MatrixSparse:resultMatrix = MatrixSparse(rowCount, columnCount, result);
}
