// Generated by OutWit.Cloud.Documents.Generator 1.0.0 from OutWit.Controller.Visualization.ParaView.Model 0.5.0.
// Do not edit: regenerate from the model assembly.
//
// OmnibusCloud job document vocabulary: paraview
//
// Every struct below is a published document type. Fill one in, then
// to_parameter_json() is the job request parameter ({"kind":"document",...})
// to place into the request's positional parameter list. Wire convention:
// camelCase keys, enum member names as strings, empty optionals omitted so
// the server applies its own defaults. UUIDs and timestamps travel as text
// (canonical UUID, ISO 8601). Header-only, C++17, standard library only.
#ifndef OMNIBUSCLOUD_DOCUMENTS_PARAVIEW_HPP
#define OMNIBUSCLOUD_DOCUMENTS_PARAVIEW_HPP

#include <charconv>
#include <cmath>
#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <type_traits>
#include <vector>

namespace omnibuscloud::documents::paraview {

inline constexpr std::string_view component = "paraview";

namespace detail {

// Minimal JSON writer: enough for the wire objects of this vocabulary.
class json_writer {
public:
    void begin_object() { separator(); out_ += '{'; first_.push_back(true); }
    void end_object() { out_ += '}'; first_.pop_back(); }
    void begin_array() { separator(); out_ += '['; first_.push_back(true); }
    void end_array() { out_ += ']'; first_.pop_back(); }

    void key(std::string_view name) {
        separator();
        write_string(name);
        out_ += ':';
        first_.back() = true;
    }

    void null_value() { separator(); out_ += "null"; }
    void value(bool v) { separator(); out_ += v ? "true" : "false"; }
    void value(std::string_view v) { separator(); write_string(v); }
    void value(const char* v) { value(std::string_view(v)); }
    void value(const std::string& v) { value(std::string_view(v)); }

    template <class T, std::enable_if_t<std::is_integral_v<T> && !std::is_same_v<T, bool>, int> = 0>
    void value(T v) {
        separator();
        char buffer[32];
        auto result = std::to_chars(buffer, buffer + sizeof(buffer), v);
        out_.append(buffer, result.ptr);
    }

    template <class T, std::enable_if_t<std::is_floating_point_v<T>, int> = 0>
    void value(T v) {
        if (!std::isfinite(v))
            throw std::invalid_argument("JSON has no representation for non-finite numbers");
        separator();
        char buffer[64];
        auto result = std::to_chars(buffer, buffer + sizeof(buffer), v);
        out_.append(buffer, result.ptr);
    }

    const std::string& str() const { return out_; }

private:
    void separator() {
        if (first_.empty())
            return;
        if (!first_.back())
            out_ += ',';
        first_.back() = false;
    }

    void write_string(std::string_view text) {
        static constexpr char hex[] = "0123456789abcdef";
        out_ += '"';
        for (unsigned char c : text) {
            switch (c) {
                case '"': out_ += "\\\""; break;
                case '\\': out_ += "\\\\"; break;
                case '\b': out_ += "\\b"; break;
                case '\f': out_ += "\\f"; break;
                case '\n': out_ += "\\n"; break;
                case '\r': out_ += "\\r"; break;
                case '\t': out_ += "\\t"; break;
                default:
                    if (c < 0x20) {
                        out_ += "\\u00";
                        out_ += hex[c >> 4];
                        out_ += hex[c & 0xF];
                    } else {
                        out_ += static_cast<char>(c);
                    }
            }
        }
        out_ += '"';
    }

    std::string out_;
    std::vector<bool> first_;
};

} // namespace detail

/// Semantic role of a package attachment. The role drives per-task attachment subsetting: a series index file rides in every task's subset, while reader inputs ride only in the subsets of the timesteps they belong to.
enum class para_view_attachment_role {
    /// A data file a reader in the state opens (a mesh, a field, one piece of a file series).
    ReaderInput,
    /// A collection/index file (for example a .pvd or a .series JSON) whose reader needs the whole index at load time; present in every task's subset while the referenced pieces stay per-timestep.
    SeriesIndex,
    /// A file the state references that is not read through a reader input (textures, lookup table presets, fonts); static, present in every task's subset.
    Auxiliary,
};

/// The wire name of a para_view_attachment_role value.
inline std::string_view to_string(para_view_attachment_role value) noexcept {
    switch (value) {
        case para_view_attachment_role::ReaderInput: return "ReaderInput";
        case para_view_attachment_role::SeriesIndex: return "SeriesIndex";
        case para_view_attachment_role::Auxiliary: return "Auxiliary";
    }
    return "";
}

/// Parses the wire name of a para_view_attachment_role value; false when the name is unknown.
inline bool try_parse(std::string_view text, para_view_attachment_role& value) noexcept {
    if (text == "ReaderInput") { value = para_view_attachment_role::ReaderInput; return true; }
    if (text == "SeriesIndex") { value = para_view_attachment_role::SeriesIndex; return true; }
    if (text == "Auxiliary") { value = para_view_attachment_role::Auxiliary; return true; }
    return false;
}

/// The direction a composed scene's camera looks from before it is fitted to the data (the standard view buttons of the GUI). The camera move of the output options (turntable) revolves this framing at render time.
enum class para_view_camera_direction {
    /// From the (+1, +1, +1) octant, Z up — the classic engineering isometric.
    Isometric,
    /// Looking along -X from +X.
    PlusX,
    /// Looking along +X from -X.
    MinusX,
    /// Looking along -Y from +Y.
    PlusY,
    /// Looking along +Y from -Y.
    MinusY,
    /// Looking along -Z from +Z (top view).
    PlusZ,
    /// Looking along +Z from -Z (bottom view).
    MinusZ,
};

/// The wire name of a para_view_camera_direction value.
inline std::string_view to_string(para_view_camera_direction value) noexcept {
    switch (value) {
        case para_view_camera_direction::Isometric: return "Isometric";
        case para_view_camera_direction::PlusX: return "PlusX";
        case para_view_camera_direction::MinusX: return "MinusX";
        case para_view_camera_direction::PlusY: return "PlusY";
        case para_view_camera_direction::MinusY: return "MinusY";
        case para_view_camera_direction::PlusZ: return "PlusZ";
        case para_view_camera_direction::MinusZ: return "MinusZ";
    }
    return "";
}

/// Parses the wire name of a para_view_camera_direction value; false when the name is unknown.
inline bool try_parse(std::string_view text, para_view_camera_direction& value) noexcept {
    if (text == "Isometric") { value = para_view_camera_direction::Isometric; return true; }
    if (text == "PlusX") { value = para_view_camera_direction::PlusX; return true; }
    if (text == "MinusX") { value = para_view_camera_direction::MinusX; return true; }
    if (text == "PlusY") { value = para_view_camera_direction::PlusY; return true; }
    if (text == "MinusY") { value = para_view_camera_direction::MinusY; return true; }
    if (text == "PlusZ") { value = para_view_camera_direction::PlusZ; return true; }
    if (text == "MinusZ") { value = para_view_camera_direction::MinusZ; return true; }
    return false;
}

/// Which timesteps a composed scene's camera framing and colour range must accommodate. The composer inspects the data at the chosen timesteps once, bakes one camera and one colour range into the state, and every rendered frame then shares them — no per-frame drift.
enum class para_view_camera_fit {
    /// The union of the data bounds and array ranges over the timeline (sampled when it is long).
    AllTimesteps,
    /// The last timestep only — the final result of a transient solve.
    LastTimestep,
    /// The first timestep only.
    FirstTimestep,
};

/// The wire name of a para_view_camera_fit value.
inline std::string_view to_string(para_view_camera_fit value) noexcept {
    switch (value) {
        case para_view_camera_fit::AllTimesteps: return "AllTimesteps";
        case para_view_camera_fit::LastTimestep: return "LastTimestep";
        case para_view_camera_fit::FirstTimestep: return "FirstTimestep";
    }
    return "";
}

/// Parses the wire name of a para_view_camera_fit value; false when the name is unknown.
inline bool try_parse(std::string_view text, para_view_camera_fit& value) noexcept {
    if (text == "AllTimesteps") { value = para_view_camera_fit::AllTimesteps; return true; }
    if (text == "LastTimestep") { value = para_view_camera_fit::LastTimestep; return true; }
    if (text == "FirstTimestep") { value = para_view_camera_fit::FirstTimestep; return true; }
    return false;
}

/// Where the array a composed scene colours by lives.
enum class para_view_color_association {
    /// A point (nodal) array — the CalculiX result blocks (NDTEMP, DISP, STRESS, ...).
    Points,
    /// A cell (element) array.
    Cells,
};

/// The wire name of a para_view_color_association value.
inline std::string_view to_string(para_view_color_association value) noexcept {
    switch (value) {
        case para_view_color_association::Points: return "Points";
        case para_view_color_association::Cells: return "Cells";
    }
    return "";
}

/// Parses the wire name of a para_view_color_association value; false when the name is unknown.
inline bool try_parse(std::string_view text, para_view_color_association& value) noexcept {
    if (text == "Points") { value = para_view_color_association::Points; return true; }
    if (text == "Cells") { value = para_view_color_association::Cells; return true; }
    return false;
}

/// How ParaViewFrameSelectionData picks the timesteps to render.
enum class para_view_frame_selection_mode {
    /// One output: the timestep at index First.
    Single,
    /// Timestep indices First..Last inclusive, every Step.
    Range,
    /// Every timestep of the state's timeline (one output for a static scene).
    All,
    /// Exactly the indices listed in Indices, in that order.
    Explicit,
};

/// The wire name of a para_view_frame_selection_mode value.
inline std::string_view to_string(para_view_frame_selection_mode value) noexcept {
    switch (value) {
        case para_view_frame_selection_mode::Single: return "Single";
        case para_view_frame_selection_mode::Range: return "Range";
        case para_view_frame_selection_mode::All: return "All";
        case para_view_frame_selection_mode::Explicit: return "Explicit";
    }
    return "";
}

/// Parses the wire name of a para_view_frame_selection_mode value; false when the name is unknown.
inline bool try_parse(std::string_view text, para_view_frame_selection_mode& value) noexcept {
    if (text == "Single") { value = para_view_frame_selection_mode::Single; return true; }
    if (text == "Range") { value = para_view_frame_selection_mode::Range; return true; }
    if (text == "All") { value = para_view_frame_selection_mode::All; return true; }
    if (text == "Explicit") { value = para_view_frame_selection_mode::Explicit; return true; }
    return false;
}

/// Image format of a rendered output. Version 1 supports the two formats the runner's SaveScreenshot path and the adapter's output validator both understand.
enum class para_view_image_format {
    /// Lossless PNG (RGB or RGBA when the background is transparent).
    Png,
    /// JPEG (RGB; transparency is not representable).
    Jpeg,
};

/// The wire name of a para_view_image_format value.
inline std::string_view to_string(para_view_image_format value) noexcept {
    switch (value) {
        case para_view_image_format::Png: return "Png";
        case para_view_image_format::Jpeg: return "Jpeg";
    }
    return "";
}

/// Parses the wire name of a para_view_image_format value; false when the name is unknown.
inline bool try_parse(std::string_view text, para_view_image_format& value) noexcept {
    if (text == "Png") { value = para_view_image_format::Png; return true; }
    if (text == "Jpeg") { value = para_view_image_format::Jpeg; return true; }
    return false;
}

/// How a composed scene draws its data (ParaView representation types).
enum class para_view_scene_representation {
    /// Shaded surface.
    Surface,
    /// Shaded surface with the mesh edges drawn.
    SurfaceWithEdges,
    /// Edges only.
    Wireframe,
};

/// The wire name of a para_view_scene_representation value.
inline std::string_view to_string(para_view_scene_representation value) noexcept {
    switch (value) {
        case para_view_scene_representation::Surface: return "Surface";
        case para_view_scene_representation::SurfaceWithEdges: return "SurfaceWithEdges";
        case para_view_scene_representation::Wireframe: return "Wireframe";
    }
    return "";
}

/// Parses the wire name of a para_view_scene_representation value; false when the name is unknown.
inline bool try_parse(std::string_view text, para_view_scene_representation& value) noexcept {
    if (text == "Surface") { value = para_view_scene_representation::Surface; return true; }
    if (text == "SurfaceWithEdges") { value = para_view_scene_representation::SurfaceWithEdges; return true; }
    if (text == "Wireframe") { value = para_view_scene_representation::Wireframe; return true; }
    return false;
}

/// The axis a camera orbit (ParaViewTurntableData) revolves about, through the view's focal point.
enum class para_view_turntable_axis {
    /// The view-up vector the state carries for the camera — the orbit keeps the user's framing exactly (the usual choice when the camera was set through the view-direction toolbar).
    ViewUp,
    /// The world X axis: the camera revolves rigidly about it through the focal point (position and view-up together), so a tilted camera keeps its tilt and the horizon stays level.
    X,
    /// The world Y axis: the camera revolves rigidly about it through the focal point (position and view-up together), so a tilted camera keeps its tilt and the horizon stays level.
    Y,
    /// The world Z axis: the camera revolves rigidly about it through the focal point (position and view-up together), so a tilted camera keeps its tilt and the horizon stays level.
    Z,
};

/// The wire name of a para_view_turntable_axis value.
inline std::string_view to_string(para_view_turntable_axis value) noexcept {
    switch (value) {
        case para_view_turntable_axis::ViewUp: return "ViewUp";
        case para_view_turntable_axis::X: return "X";
        case para_view_turntable_axis::Y: return "Y";
        case para_view_turntable_axis::Z: return "Z";
    }
    return "";
}

/// Parses the wire name of a para_view_turntable_axis value; false when the name is unknown.
inline bool try_parse(std::string_view text, para_view_turntable_axis& value) noexcept {
    if (text == "ViewUp") { value = para_view_turntable_axis::ViewUp; return true; }
    if (text == "X") { value = para_view_turntable_axis::X; return true; }
    if (text == "Y") { value = para_view_turntable_axis::Y; return true; }
    if (text == "Z") { value = para_view_turntable_axis::Z; return true; }
    return false;
}

/// How a camera orbit (ParaViewTurntableData) composes with the selected timesteps.
enum class para_view_turntable_time_mode {
    /// The data time stands still while the camera orbits: every selected timestep receives a full orbit of Frames outputs (usually one timestep in, one showcase orbit out).
    Fixed,
    /// The data time advances along the selected timesteps while the camera completes one orbit: exactly Frames outputs, the first at the first selected timestep, the last at the last, timesteps spread evenly in between (repeated or skipped as the counts dictate).
    Advancing,
};

/// The wire name of a para_view_turntable_time_mode value.
inline std::string_view to_string(para_view_turntable_time_mode value) noexcept {
    switch (value) {
        case para_view_turntable_time_mode::Fixed: return "Fixed";
        case para_view_turntable_time_mode::Advancing: return "Advancing";
    }
    return "";
}

/// Parses the wire name of a para_view_turntable_time_mode value; false when the name is unknown.
inline bool try_parse(std::string_view text, para_view_turntable_time_mode& value) noexcept {
    if (text == "Fixed") { value = para_view_turntable_time_mode::Fixed; return true; }
    if (text == "Advancing") { value = para_view_turntable_time_mode::Advancing; return true; }
    return false;
}

/// One content-addressed file of a visualization package: the blob that holds it, the normalized logical path the state refers to it by, its digest and size, its semantic role, and the file-series metadata that drives per-task attachment subsetting.
/// Document type paraview.attachmentRef@1.
struct paraview_attachment_ref {
    static constexpr std::string_view type_id = "paraview.attachmentRef@1";

    /// Blob identifier of the uploaded file content.
    std::optional<std::string> blob_id;
    /// Normalized logical path inside the package: relative, '/'-separated, no '..', no drive letter, no URI scheme. The state refers to the file by exactly this path, and the node materializes the file at exactly this path under the task's package root.
    std::optional<std::string> logical_path;
    /// Lower-case hexadecimal SHA-256 digest of the file content.
    std::optional<std::string> sha256;
    /// Declared byte size of the file content.
    std::optional<int64_t> size;
    /// Semantic role of the file.
    std::optional<para_view_attachment_role> role;
    /// Name of the file-series group the file belongs to (for example the reader's registration name); empty for a file that is not part of a series.
    std::optional<std::string> series_group;
    /// Indices into the state's timeline at which this file is displayed. Empty means the file applies to every timestep (static meshes, non-series inputs, indexes). A series member with an empty list is a series whose format gives no per-timestep association: the whole group is shipped to every task and the fallback is recorded in the validation report.
    std::vector<int32_t> timestep_indices;
    /// Position of the file inside its series group (ordering metadata, informational).
    std::optional<int32_t> series_ordinal;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (blob_id) {
            w.key("blobId");
            w.value((*blob_id));
        }
        if (logical_path) {
            w.key("logicalPath");
            w.value((*logical_path));
        }
        if (sha256) {
            w.key("sha256");
            w.value((*sha256));
        }
        if (size) {
            w.key("size");
            w.value((*size));
        }
        if (role) {
            w.key("role");
            w.value(to_string((*role)));
        }
        if (series_group) {
            w.key("seriesGroup");
            w.value((*series_group));
        }
        w.key("timestepIndices");
        w.begin_array();
        for (const auto& item0 : timestep_indices) {
            w.value(item0);
        }
        w.end_array();
        if (series_ordinal) {
            w.key("seriesOrdinal");
            w.value((*series_ordinal));
        }
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"paraview.attachmentRef@1\",\"value\":") + to_json() + "}";
    }
};

/// A scene to be COMPOSED on the fleet from bare data (docs 06, part A): one blob-referenced data attachment plus the presentation choices a user makes in the GUI's first minute — what to colour by, which colour map, surface or edges, whether to show the scalar bar, where the camera looks from and which timesteps it must fit. ParaView.Compose turns it into an ordinary ParaViewSceneRefData (a real saved state ParaView wrote itself) on one node, and the unchanged validate → split → render chain takes it from there. Nothing here is a path, a script, or a proxy definition: every member is a bounded value the composer maps onto ParaView API calls, never onto code.
/// Document type paraview.dataScene@1.
struct paraview_data_scene {
    static constexpr std::string_view type_id = "paraview.dataScene@1";

    /// The data the scene is composed from, as blob references with logical paths. Version 1 admits exactly one ReaderInput CalculiX .frd result; its Sha256 and Size may be left empty — the composer stamps the values it materialized.
    std::vector<paraview_attachment_ref> attachments;
    /// The data array to colour the surface by (for example NDTEMP, DISP, STRESS). Empty selects the first point array the data carries; a named array that the data does not carry fails the composition (the job reports the arrays that exist).
    std::optional<std::string> color_array_name;
    /// Whether ColorArrayName names a point or a cell array.
    std::optional<para_view_color_association> color_association;
    /// The component of a multi-component array to colour by: -1 for the magnitude (the default), otherwise the zero-based component index.
    std::optional<int32_t> color_component;
    /// A ParaView colour-map preset name from the controller's allowlist (for example Cool to Warm, Viridis (matplotlib), Jet); empty keeps ParaView's default.
    std::optional<std::string> colormap_preset;
    /// How the data is drawn.
    std::optional<para_view_scene_representation> representation;
    /// Whether the colour legend (scalar bar) of the coloured array is shown.
    std::optional<bool> show_scalar_bar;
    /// The direction the camera looks from before it is fitted to the data.
    std::optional<para_view_camera_direction> camera_direction;
    /// Which timesteps the camera (and the colour range) must accommodate.
    std::optional<para_view_camera_fit> fit_to;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        w.key("attachments");
        w.begin_array();
        for (const auto& item0 : attachments) {
            item0.write_json(w);
        }
        w.end_array();
        if (color_array_name) {
            w.key("colorArrayName");
            w.value((*color_array_name));
        }
        if (color_association) {
            w.key("colorAssociation");
            w.value(to_string((*color_association)));
        }
        if (color_component) {
            w.key("colorComponent");
            w.value((*color_component));
        }
        if (colormap_preset) {
            w.key("colormapPreset");
            w.value((*colormap_preset));
        }
        if (representation) {
            w.key("representation");
            w.value(to_string((*representation)));
        }
        if (show_scalar_bar) {
            w.key("showScalarBar");
            w.value((*show_scalar_bar));
        }
        if (camera_direction) {
            w.key("cameraDirection");
            w.value(to_string((*camera_direction)));
        }
        if (fit_to) {
            w.key("fitTo");
            w.value(to_string((*fit_to)));
        }
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"paraview.dataScene@1\",\"value\":") + to_json() + "}";
    }
};

/// Which timesteps of the state's timeline to render. Indices refer to the resolved timeline (the state's TimeKeeper); a static scene has exactly one timestep, index 0.
/// Document type paraview.frameSelection@1.
struct paraview_frame_selection {
    static constexpr std::string_view type_id = "paraview.frameSelection@1";

    /// Selection mode.
    std::optional<para_view_frame_selection_mode> mode;
    /// First timestep index (Single: the only index; Range: the start).
    std::optional<int32_t> first;
    /// Last timestep index, inclusive (Range only).
    std::optional<int32_t> last;
    /// Index stride (Range only; at least 1).
    std::optional<int32_t> step;
    /// Explicit timestep indices, in render order (Explicit only).
    std::vector<int32_t> indices;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (mode) {
            w.key("mode");
            w.value(to_string((*mode)));
        }
        if (first) {
            w.key("first");
            w.value((*first));
        }
        if (last) {
            w.key("last");
            w.value((*last));
        }
        if (step) {
            w.key("step");
            w.value((*step));
        }
        w.key("indices");
        w.begin_array();
        for (const auto& item0 : indices) {
            w.value(item0);
        }
        w.end_array();
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"paraview.frameSelection@1\",\"value\":") + to_json() + "}";
    }
};

/// A camera move as an output option — the turntable of controller 0.2.0 generalised in 0.4.0 (docs 06, part B): the controller renders Frames outputs with the state's camera moved about the focal point — revolved by Degrees in total about the orbit axis, raised by ElevationDegrees in total about the camera's right axis, and moved toward or away from the focal point until its distance is DollyFactor times the start — at a fixed or an advancing data time (TimeMode). Every move is an output-side transform of the captured camera: no animation track in the state, one timestep in gives a showcase sequence out. The azimuth of output i of N is Degrees * i / N (the last output stops short of the first, so a 360° orbit loops); elevation and dolly progress as i / (N - 1) so the last output reaches the full move. With Oscillate every component sways instead: sin(2πi/N) / 2 of its total, back and forth around the captured framing, a seamless loop. The presets of a client (orbit, rise, spiral, approach, rock) are combinations of these members.
/// Document type paraview.turntable@1.
struct paraview_turntable {
    static constexpr std::string_view type_id = "paraview.turntable@1";

    /// Number of orbit outputs (at least 1; bounded by the per-job output limit together with the selected timesteps).
    std::optional<int32_t> frames;
    /// Total sweep of the orbit in degrees; the sign sets the direction (positive = the camera moves counter-clockwise seen from the orbit axis). Zero when the move has no orbit (a pure rise or approach); at most ten full turns either way.
    std::optional<double> degrees;
    /// How the orbit composes with the selected timesteps.
    std::optional<para_view_turntable_time_mode> time_mode;
    /// The orbit axis through the focal point.
    std::optional<para_view_turntable_axis> axis;
    /// Total rise of the camera in degrees about its own right axis through the focal point (positive = the camera climbs toward the view-up, toward a top-down view; negative = it dives). 0 keeps the captured height; at most ±170 so the move never crosses the pole. Appended in Model 0.4.0.
    std::optional<double> elevation_degrees;
    /// The camera's distance to the focal point at the end of the move, relative to the captured distance: 0.5 halves it (an approach), 2 doubles it (a retreat), 1 keeps it. Between 0.05 and 20. Appended in Model 0.4.0.
    std::optional<double> dolly_factor;
    /// Whether the move sways back and forth around the captured framing (a seamless rocking loop: every component follows sin(2πi/N) / 2 of its total) instead of progressing from the captured framing to the full move. Appended in Model 0.4.0.
    std::optional<bool> oscillate;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (frames) {
            w.key("frames");
            w.value((*frames));
        }
        if (degrees) {
            w.key("degrees");
            w.value((*degrees));
        }
        if (time_mode) {
            w.key("timeMode");
            w.value(to_string((*time_mode)));
        }
        if (axis) {
            w.key("axis");
            w.value(to_string((*axis)));
        }
        if (elevation_degrees) {
            w.key("elevationDegrees");
            w.value((*elevation_degrees));
        }
        if (dolly_factor) {
            w.key("dollyFactor");
            w.value((*dolly_factor));
        }
        if (oscillate) {
            w.key("oscillate");
            w.value((*oscillate));
        }
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"paraview.turntable@1\",\"value\":") + to_json() + "}";
    }
};

/// What to render from the package: the view, the output size and format, and the timesteps. Everything except Frames and Turntable is per-output and participates in the task identity; the frame selection and the turntable determine the task set (a turntable task additionally carries its orbit position in its identity).
/// Document type paraview.outputOptions@1.
struct paraview_output_options {
    static constexpr std::string_view type_id = "paraview.outputOptions@1";

    /// Registration name of the render view to capture (the state's views collection, for example RenderView1). Empty selects the state's first render view; the validation report records the resolved name.
    std::optional<std::string> view_id;
    /// Output width in pixels.
    std::optional<int32_t> width;
    /// Output height in pixels.
    std::optional<int32_t> height;
    /// Output image format.
    std::optional<para_view_image_format> format;
    /// Render with a transparent background (PNG only; ignored for JPEG).
    std::optional<bool> transparent_background;
    /// Timesteps to render.
    std::optional<paraview_frame_selection> frames;
    /// Optional camera orbit (turntable): null renders the captured camera as is. Appended in Model 0.2.0; an older reader ignores it, an older writer leaves it null.
    std::optional<paraview_turntable> turntable;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (view_id) {
            w.key("viewId");
            w.value((*view_id));
        }
        if (width) {
            w.key("width");
            w.value((*width));
        }
        if (height) {
            w.key("height");
            w.value((*height));
        }
        if (format) {
            w.key("format");
            w.value(to_string((*format)));
        }
        if (transparent_background) {
            w.key("transparentBackground");
            w.value((*transparent_background));
        }
        if (frames) {
            w.key("frames");
            (*frames).write_json(w);
        }
        if (turntable) {
            w.key("turntable");
            (*turntable).write_json(w);
        }
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"paraview.outputOptions@1\",\"value\":") + to_json() + "}";
    }
};

/// A non-built-in ParaView plugin the state requires. Version 1 admits exactly one entry: the OmnibusCloud .frd reader at a version the bundled reader satisfies.
/// Document type paraview.pluginRequirement@1.
struct paraview_plugin_requirement {
    static constexpr std::string_view type_id = "paraview.pluginRequirement@1";

    /// Plugin name as ParaView registers it (for example OmnibusCloudFrdReader).
    std::optional<std::string> name;
    /// Minimum plugin version the state was produced with, as major.minor[.patch].
    std::optional<std::string> version;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (name) {
            w.key("name");
            w.value((*name));
        }
        if (version) {
            w.key("version");
            w.value((*version));
        }
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"paraview.pluginRequirement@1\",\"value\":") + to_json() + "}";
    }
};

/// Result of rendering one task: the task identity it answers, the output image blob, the validated output dimensions and size, and the exact backend versions that produced it.
/// Document type paraview.renderResult@1.
struct paraview_render_result {
    static constexpr std::string_view type_id = "paraview.renderResult@1";

    /// Identity of the task this result answers.
    std::optional<std::string> task_id;
    /// Ordinal of the task (Collect restores this order).
    std::optional<int32_t> task_index;
    /// Registration name of the rendered view.
    std::optional<std::string> view_id;
    /// Rendered timestep index.
    std::optional<int32_t> timestep_index;
    /// Rendered physical time value; null for a static scene.
    std::optional<double> time_value;
    /// Blob identifier of the rendered image.
    std::optional<std::string> image_blob_id;
    /// Validated output width in pixels.
    std::optional<int32_t> width;
    /// Validated output height in pixels.
    std::optional<int32_t> height;
    /// Output image format.
    std::optional<para_view_image_format> format;
    /// Output byte size.
    std::optional<int64_t> byte_size;
    /// Exact ParaView runtime version that rendered the task (for example 6.1.1).
    std::optional<std::string> runtime_version;
    /// Version of the bundled OmnibusCloud reader loaded for the task; empty when no plugin was loaded.
    std::optional<std::string> reader_version;
    /// Wall-clock seconds of the runner process.
    std::optional<double> render_seconds;
    /// Bounded diagnostic text from the runner (never the full process output).
    std::optional<std::string> diagnostics;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (task_id) {
            w.key("taskId");
            w.value((*task_id));
        }
        if (task_index) {
            w.key("taskIndex");
            w.value((*task_index));
        }
        if (view_id) {
            w.key("viewId");
            w.value((*view_id));
        }
        if (timestep_index) {
            w.key("timestepIndex");
            w.value((*timestep_index));
        }
        if (time_value) {
            w.key("timeValue");
            w.value((*time_value));
        }
        if (image_blob_id) {
            w.key("imageBlobId");
            w.value((*image_blob_id));
        }
        if (width) {
            w.key("width");
            w.value((*width));
        }
        if (height) {
            w.key("height");
            w.value((*height));
        }
        if (format) {
            w.key("format");
            w.value(to_string((*format)));
        }
        if (byte_size) {
            w.key("byteSize");
            w.value((*byte_size));
        }
        if (runtime_version) {
            w.key("runtimeVersion");
            w.value((*runtime_version));
        }
        if (reader_version) {
            w.key("readerVersion");
            w.value((*reader_version));
        }
        if (render_seconds) {
            w.key("renderSeconds");
            w.value((*render_seconds));
        }
        if (diagnostics) {
            w.key("diagnostics");
            w.value((*diagnostics));
        }
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"paraview.renderResult@1\",\"value\":") + to_json() + "}";
    }
};

/// What the package was produced with and what it needs to be rendered: the producing ParaView version (exact major and minor are mandatory in the version-1 compatibility policy), the producing plugin and platform (provenance), and the non-built-in plugins the state requires.
/// Document type paraview.runtimeRequirement@1.
struct paraview_runtime_requirement {
    static constexpr std::string_view type_id = "paraview.runtimeRequirement@1";

    /// Major version of the ParaView that produced the state.
    std::optional<int32_t> para_view_major;
    /// Minor version of the ParaView that produced the state.
    std::optional<int32_t> para_view_minor;
    /// Patch version of the ParaView that produced the state (informational; patch mismatch is tolerated).
    std::optional<int32_t> para_view_patch;
    /// Version of the producing OmnibusCloud ParaView plugin (provenance).
    std::optional<std::string> producer_plugin_version;
    /// Runtime identifier of the producing platform, for example win-x64 (provenance).
    std::optional<std::string> producer_platform;
    /// Non-built-in plugins the state requires. Unknown names are rejected; version 1 allowlists only the bundled OmnibusCloud reader.
    std::vector<paraview_plugin_requirement> plugins;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (para_view_major) {
            w.key("paraViewMajor");
            w.value((*para_view_major));
        }
        if (para_view_minor) {
            w.key("paraViewMinor");
            w.value((*para_view_minor));
        }
        if (para_view_patch) {
            w.key("paraViewPatch");
            w.value((*para_view_patch));
        }
        if (producer_plugin_version) {
            w.key("producerPluginVersion");
            w.value((*producer_plugin_version));
        }
        if (producer_platform) {
            w.key("producerPlatform");
            w.value((*producer_platform));
        }
        w.key("plugins");
        w.begin_array();
        for (const auto& item0 : plugins) {
            item0.write_json(w);
        }
        w.end_array();
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"paraview.runtimeRequirement@1\",\"value\":") + to_json() + "}";
    }
};

/// Blob-backed reference to an OmnibusCloud ParaView package: the saved state (.pvsm) blob, every content-addressed attachment the state refers to by logical path, the runtime requirements, and the producer's view of the timeline. The package is validated server-side independently of any plugin-side validation; the controller never uses a client absolute path.
/// Document type paraview.sceneRef@1.
struct paraview_scene_ref {
    static constexpr std::string_view type_id = "paraview.sceneRef@1";

    /// Blob identifier of the saved ParaView state (.pvsm).
    std::optional<std::string> state_blob_id;
    /// Lower-case hexadecimal SHA-256 digest of the state file; verified against the blob before validation.
    std::optional<std::string> state_sha256;
    /// Declared byte size of the state file.
    std::optional<int64_t> state_size;
    /// Every file the state refers to, by normalized logical path, with digest, size, role, and series metadata.
    std::vector<paraview_attachment_ref> attachments;
    /// Producing ParaView version and required plugins.
    std::optional<paraview_runtime_requirement> runtime;
    /// The timeline (TimeKeeper timestep values) as the producer saw it. The state's own TimeKeeper is authoritative when the state carries one; the validation report records the resolved timeline. Empty for a static scene.
    std::vector<double> timestep_values;
    /// The producer's package manifest (com.omnibuscloud.paraview-package) as opaque provenance, bounded in size. It never drives a controller decision — the typed members above do.
    std::optional<std::string> package_manifest_json;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (state_blob_id) {
            w.key("stateBlobId");
            w.value((*state_blob_id));
        }
        if (state_sha256) {
            w.key("stateSha256");
            w.value((*state_sha256));
        }
        if (state_size) {
            w.key("stateSize");
            w.value((*state_size));
        }
        w.key("attachments");
        w.begin_array();
        for (const auto& item0 : attachments) {
            item0.write_json(w);
        }
        w.end_array();
        if (runtime) {
            w.key("runtime");
            (*runtime).write_json(w);
        }
        w.key("timestepValues");
        w.begin_array();
        for (const auto& item0 : timestep_values) {
            w.value(item0);
        }
        w.end_array();
        if (package_manifest_json) {
            w.key("packageManifestJson");
            w.value((*package_manifest_json));
        }
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"paraview.sceneRef@1\",\"value\":") + to_json() + "}";
    }
};

/// Outcome of ParaView.Validate: whether the package, state, and options are admissible, every error and warning found, the subsetting fallbacks recorded, and the resolved rendering plan (view, timeline, timestep indices, output size) that ParaView.Split turns into tasks.
/// Document type paraview.validationReport@1.
struct paraview_validation_report {
    static constexpr std::string_view type_id = "paraview.validationReport@1";

    /// True when no error was found; Split refuses an invalid report.
    std::optional<bool> is_valid;
    /// Permanent input failures (the job must not retry).
    std::vector<std::string> errors;
    /// Non-fatal findings.
    std::vector<std::string> warnings;
    /// Series groups that fell back to full-set transfer because their format gives no per-timestep association.
    std::vector<std::string> fallbacks;
    /// Digest of the whole package (state + attachments) — the first component of every task identity.
    std::optional<std::string> package_digest;
    /// Registration name of the view that will be rendered.
    std::optional<std::string> resolved_view_id;
    /// Timestep indices that will be rendered, in render order.
    std::vector<int32_t> resolved_timestep_indices;
    /// The resolved timeline (TimeKeeper values); empty for a static scene.
    std::vector<double> timestep_values;
    /// Number of attachments in the package.
    std::optional<int32_t> attachment_count;
    /// Sum of the declared attachment sizes plus the state size.
    std::optional<int64_t> total_attachment_bytes;
    /// Distinct proxy types the state instantiates, as group/type, sorted.
    std::vector<std::string> proxy_types;
    /// Plugin requirements of the package, as name@version.
    std::vector<std::string> required_plugins;
    /// The ParaView runtime version the controller will render with.
    std::optional<std::string> runtime_version;
    /// Resolved output width in pixels.
    std::optional<int32_t> width;
    /// Resolved output height in pixels.
    std::optional<int32_t> height;
    /// Resolved output format.
    std::optional<para_view_image_format> format;
    /// Logical paths of the series anchors — the first file of every series group, which ParaView's series readers open at load and which therefore ships with every task.
    std::vector<std::string> series_anchors;
    /// Number of outputs (tasks) the job will render: the resolved timesteps, multiplied or replaced by the turntable's orbit frames. 0 when the package is invalid. Appended in Model 0.2.0.
    std::optional<int32_t> output_count;

    /// Writes the wire object of this value into a writer.
    void write_json(detail::json_writer& w) const {
        w.begin_object();
        if (is_valid) {
            w.key("isValid");
            w.value((*is_valid));
        }
        w.key("errors");
        w.begin_array();
        for (const auto& item0 : errors) {
            w.value(item0);
        }
        w.end_array();
        w.key("warnings");
        w.begin_array();
        for (const auto& item0 : warnings) {
            w.value(item0);
        }
        w.end_array();
        w.key("fallbacks");
        w.begin_array();
        for (const auto& item0 : fallbacks) {
            w.value(item0);
        }
        w.end_array();
        if (package_digest) {
            w.key("packageDigest");
            w.value((*package_digest));
        }
        if (resolved_view_id) {
            w.key("resolvedViewId");
            w.value((*resolved_view_id));
        }
        w.key("resolvedTimestepIndices");
        w.begin_array();
        for (const auto& item0 : resolved_timestep_indices) {
            w.value(item0);
        }
        w.end_array();
        w.key("timestepValues");
        w.begin_array();
        for (const auto& item0 : timestep_values) {
            w.value(item0);
        }
        w.end_array();
        if (attachment_count) {
            w.key("attachmentCount");
            w.value((*attachment_count));
        }
        if (total_attachment_bytes) {
            w.key("totalAttachmentBytes");
            w.value((*total_attachment_bytes));
        }
        w.key("proxyTypes");
        w.begin_array();
        for (const auto& item0 : proxy_types) {
            w.value(item0);
        }
        w.end_array();
        w.key("requiredPlugins");
        w.begin_array();
        for (const auto& item0 : required_plugins) {
            w.value(item0);
        }
        w.end_array();
        if (runtime_version) {
            w.key("runtimeVersion");
            w.value((*runtime_version));
        }
        if (width) {
            w.key("width");
            w.value((*width));
        }
        if (height) {
            w.key("height");
            w.value((*height));
        }
        if (format) {
            w.key("format");
            w.value(to_string((*format)));
        }
        w.key("seriesAnchors");
        w.begin_array();
        for (const auto& item0 : series_anchors) {
            w.value(item0);
        }
        w.end_array();
        if (output_count) {
            w.key("outputCount");
            w.value((*output_count));
        }
        w.end_object();
    }

    /// The wire object of this value (camelCase, enum names, empty optionals omitted).
    std::string to_json() const {
        detail::json_writer w;
        write_json(w);
        return w.str();
    }

    /// This value as a job request parameter of kind "document".
    std::string to_parameter_json() const {
        return std::string("{\"kind\":\"document\",\"type\":\"paraview.validationReport@1\",\"value\":") + to_json() + "}";
    }
};

/// Every published type id of the component.
inline constexpr std::string_view type_ids[] = {
    "paraview.attachmentRef@1",
    "paraview.dataScene@1",
    "paraview.frameSelection@1",
    "paraview.outputOptions@1",
    "paraview.pluginRequirement@1",
    "paraview.renderResult@1",
    "paraview.runtimeRequirement@1",
    "paraview.sceneRef@1",
    "paraview.turntable@1",
    "paraview.validationReport@1",
};

} // namespace omnibuscloud::documents::paraview

#endif // OMNIBUSCLOUD_DOCUMENTS_PARAVIEW_HPP
