# Generated by OutWit.Cloud.Documents.Generator 1.0.0 from OutWit.Controller.Visualization.ParaView.Model 0.1.0.
# Do not edit: regenerate from the model assembly.
#
# OmnibusCloud job document vocabulary: paraview
#
# Every dataclass below is a published document type. Build one, then
# to_parameter() gives the job request parameter ({"kind": "document", ...})
# to place into the request's positional parameter list; from_json() reads
# a value document's "value" back into the typed object. Wire convention:
# camelCase keys, enum member names as strings, None properties omitted.
# Optional fields left as None are omitted, which lets the server apply its
# own defaults; a field the server marks required has no default here.
#
# Standard library only, Python 3.10+ (keyword-only dataclasses); no OmnibusCloud
# SDK import is needed to use it.
from __future__ import annotations

import datetime as _datetime
import enum as _enum
import re as _re
import uuid as _uuid
from dataclasses import dataclass as _dataclass
from dataclasses import field as _field
from typing import Any as _Any
from typing import ClassVar as _ClassVar
from typing import Optional as _Optional

COMPONENT = "paraview"
"""The component whose vocabulary this module binds."""

TYPE_IDS = (
    "paraview.attachmentRef@1",
    "paraview.frameSelection@1",
    "paraview.outputOptions@1",
    "paraview.pluginRequirement@1",
    "paraview.renderResult@1",
    "paraview.runtimeRequirement@1",
    "paraview.sceneRef@1",
    "paraview.validationReport@1",
)
"""Every published type id of the component."""


_FRACTION = _re.compile(r"(\.\d{6})\d+")


def _omit_none(values: dict) -> dict:
    return {key: value for key, value in values.items() if value is not None}


def _enum_to_json(value: _Any) -> _Any:
    return value.value if isinstance(value, _enum.Enum) else value


def _enum_from_json(enum_type: type, value: _Any) -> _Any:
    # A member name this binding does not know (newer server) is kept as text.
    try:
        return enum_type(value)
    except ValueError:
        return value


def _uuid_to_json(value: _Any) -> str:
    return str(value)


def _uuid_from_json(value: _Any) -> _uuid.UUID:
    return value if isinstance(value, _uuid.UUID) else _uuid.UUID(str(value))


def _datetime_to_json(value: _Any) -> str:
    # The server's form: ISO 8601, fraction only when non-zero and without
    # trailing zeros, 'Z' for UTC, offset otherwise, nothing for naive values.
    if isinstance(value, str):
        return value
    text = value.strftime("%Y-%m-%dT%H:%M:%S")
    if value.microsecond:
        text += "." + f"{value.microsecond:06d}".rstrip("0")
    offset = value.utcoffset()
    if offset is None:
        return text
    if offset == _datetime.timedelta(0):
        return text + "Z"
    total = int(offset.total_seconds())
    sign = "+" if total >= 0 else "-"
    total = abs(total)
    return text + f"{sign}{total // 3600:02d}:{(total % 3600) // 60:02d}"


def _datetime_from_json(value: _Any) -> _datetime.datetime:
    if isinstance(value, _datetime.datetime):
        return value
    text = str(value)
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    # .NET writes seven fractional digits; Python parses at most six.
    return _datetime.datetime.fromisoformat(_FRACTION.sub(r"\1", text))


class ParaViewAttachmentRole(str, _enum.Enum):
    """Semantic role of a package attachment. The role drives per-task attachment subsetting: a series index file rides in every task's subset, while reader inputs ride only in the subsets of the timesteps they belong to."""

    #: A data file a reader in the state opens (a mesh, a field, one piece of a file series).
    ReaderInput = "ReaderInput"
    #: A collection/index file (for example a .pvd or a .series JSON) whose reader needs the whole index at load time; present in every task's subset while the referenced pieces stay per-timestep.
    SeriesIndex = "SeriesIndex"
    #: A file the state references that is not read through a reader input (textures, lookup table presets, fonts); static, present in every task's subset.
    Auxiliary = "Auxiliary"


class ParaViewFrameSelectionMode(str, _enum.Enum):
    """How ParaViewFrameSelectionData picks the timesteps to render."""

    #: One output: the timestep at index First.
    Single = "Single"
    #: Timestep indices First..Last inclusive, every Step.
    Range = "Range"
    #: Every timestep of the state's timeline (one output for a static scene).
    All = "All"
    #: Exactly the indices listed in Indices, in that order.
    Explicit = "Explicit"


class ParaViewImageFormat(str, _enum.Enum):
    """Image format of a rendered output. Version 1 supports the two formats the runner's SaveScreenshot path and the adapter's output validator both understand."""

    #: Lossless PNG (RGB or RGBA when the background is transparent).
    Png = "Png"
    #: JPEG (RGB; transparency is not representable).
    Jpeg = "Jpeg"


@_dataclass(kw_only=True)
class ParaviewAttachmentRef:
    """One content-addressed file of a visualization package: the blob that holds it, the normalized logical path the state refers to it by, its digest and size, its semantic role, and the file-series metadata that drives per-task attachment subsetting."""

    TYPE_ID: _ClassVar[str] = "paraview.attachmentRef@1"
    """The published type id this class binds."""

    #: Blob identifier of the uploaded file content.
    blob_id: _Optional[_uuid.UUID] = None
    #: Normalized logical path inside the package: relative, '/'-separated, no '..', no drive letter, no URI scheme. The state refers to the file by exactly this path, and the node materializes the file at exactly this path under the task's package root.
    logical_path: _Optional[str] = None
    #: Lower-case hexadecimal SHA-256 digest of the file content.
    sha256: _Optional[str] = None
    #: Declared byte size of the file content.
    size: _Optional[int] = None
    #: Semantic role of the file.
    role: _Optional[ParaViewAttachmentRole] = None
    #: Name of the file-series group the file belongs to (for example the reader's registration name); empty for a file that is not part of a series.
    series_group: _Optional[str] = None
    #: Indices into the state's timeline at which this file is displayed. Empty means the file applies to every timestep (static meshes, non-series inputs, indexes). A series member with an empty list is a series whose format gives no per-timestep association: the whole group is shipped to every task and the fallback is recorded in the validation report.
    timestep_indices: list[int] = _field(default_factory=list)
    #: Position of the file inside its series group (ordering metadata, informational).
    series_ordinal: _Optional[int] = None

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "blobId": (None if self.blob_id is None else _uuid_to_json(self.blob_id)),
            "logicalPath": self.logical_path,
            "sha256": self.sha256,
            "size": self.size,
            "role": (None if self.role is None else _enum_to_json(self.role)),
            "seriesGroup": self.series_group,
            "timestepIndices": (None if self.timestep_indices is None else list(self.timestep_indices)),
            "seriesOrdinal": self.series_ordinal,
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "ParaviewAttachmentRef":
        """Reads the wire object of a value document."""
        return cls(
            blob_id=(None if data.get("blobId") is None else _uuid_from_json(data.get("blobId"))),
            logical_path=data.get("logicalPath"),
            sha256=data.get("sha256"),
            size=data.get("size"),
            role=(None if data.get("role") is None else _enum_from_json(ParaViewAttachmentRole, data.get("role"))),
            series_group=data.get("seriesGroup"),
            timestep_indices=([] if data.get("timestepIndices") is None else list(data.get("timestepIndices"))),
            series_ordinal=data.get("seriesOrdinal"),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class ParaviewFrameSelection:
    """Which timesteps of the state's timeline to render. Indices refer to the resolved timeline (the state's TimeKeeper); a static scene has exactly one timestep, index 0."""

    TYPE_ID: _ClassVar[str] = "paraview.frameSelection@1"
    """The published type id this class binds."""

    #: Selection mode.
    mode: _Optional[ParaViewFrameSelectionMode] = None
    #: First timestep index (Single: the only index; Range: the start).
    first: _Optional[int] = None
    #: Last timestep index, inclusive (Range only).
    last: _Optional[int] = None
    #: Index stride (Range only; at least 1).
    step: _Optional[int] = None
    #: Explicit timestep indices, in render order (Explicit only).
    indices: list[int] = _field(default_factory=list)

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "mode": (None if self.mode is None else _enum_to_json(self.mode)),
            "first": self.first,
            "last": self.last,
            "step": self.step,
            "indices": (None if self.indices is None else list(self.indices)),
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "ParaviewFrameSelection":
        """Reads the wire object of a value document."""
        return cls(
            mode=(None if data.get("mode") is None else _enum_from_json(ParaViewFrameSelectionMode, data.get("mode"))),
            first=data.get("first"),
            last=data.get("last"),
            step=data.get("step"),
            indices=([] if data.get("indices") is None else list(data.get("indices"))),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class ParaviewOutputOptions:
    """What to render from the package: the view, the output size and format, and the timesteps. Everything except Frames is per-output and participates in the task identity; the frame selection determines the task set."""

    TYPE_ID: _ClassVar[str] = "paraview.outputOptions@1"
    """The published type id this class binds."""

    #: Registration name of the render view to capture (the state's views collection, for example RenderView1). Empty selects the state's first render view; the validation report records the resolved name.
    view_id: _Optional[str] = None
    #: Output width in pixels.
    width: _Optional[int] = None
    #: Output height in pixels.
    height: _Optional[int] = None
    #: Output image format.
    format: _Optional[ParaViewImageFormat] = None
    #: Render with a transparent background (PNG only; ignored for JPEG).
    transparent_background: _Optional[bool] = None
    #: Timesteps to render.
    frames: _Optional[ParaviewFrameSelection] = None

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "viewId": self.view_id,
            "width": self.width,
            "height": self.height,
            "format": (None if self.format is None else _enum_to_json(self.format)),
            "transparentBackground": self.transparent_background,
            "frames": (None if self.frames is None else self.frames.to_json()),
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "ParaviewOutputOptions":
        """Reads the wire object of a value document."""
        return cls(
            view_id=data.get("viewId"),
            width=data.get("width"),
            height=data.get("height"),
            format=(None if data.get("format") is None else _enum_from_json(ParaViewImageFormat, data.get("format"))),
            transparent_background=data.get("transparentBackground"),
            frames=(None if data.get("frames") is None else ParaviewFrameSelection.from_json(data.get("frames"))),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class ParaviewPluginRequirement:
    """A non-built-in ParaView plugin the state requires. Version 1 admits exactly one entry: the OmnibusCloud .frd reader at a version the bundled reader satisfies."""

    TYPE_ID: _ClassVar[str] = "paraview.pluginRequirement@1"
    """The published type id this class binds."""

    #: Plugin name as ParaView registers it (for example OmnibusCloudFrdReader).
    name: _Optional[str] = None
    #: Minimum plugin version the state was produced with, as major.minor[.patch].
    version: _Optional[str] = None

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "name": self.name,
            "version": self.version,
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "ParaviewPluginRequirement":
        """Reads the wire object of a value document."""
        return cls(
            name=data.get("name"),
            version=data.get("version"),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class ParaviewRenderResult:
    """Result of rendering one task: the task identity it answers, the output image blob, the validated output dimensions and size, and the exact backend versions that produced it."""

    TYPE_ID: _ClassVar[str] = "paraview.renderResult@1"
    """The published type id this class binds."""

    #: Identity of the task this result answers.
    task_id: _Optional[str] = None
    #: Ordinal of the task (Collect restores this order).
    task_index: _Optional[int] = None
    #: Registration name of the rendered view.
    view_id: _Optional[str] = None
    #: Rendered timestep index.
    timestep_index: _Optional[int] = None
    #: Rendered physical time value; null for a static scene.
    time_value: _Optional[float] = None
    #: Blob identifier of the rendered image.
    image_blob_id: _Optional[_uuid.UUID] = None
    #: Validated output width in pixels.
    width: _Optional[int] = None
    #: Validated output height in pixels.
    height: _Optional[int] = None
    #: Output image format.
    format: _Optional[ParaViewImageFormat] = None
    #: Output byte size.
    byte_size: _Optional[int] = None
    #: Exact ParaView runtime version that rendered the task (for example 6.1.1).
    runtime_version: _Optional[str] = None
    #: Version of the bundled OmnibusCloud reader loaded for the task; empty when no plugin was loaded.
    reader_version: _Optional[str] = None
    #: Wall-clock seconds of the runner process.
    render_seconds: _Optional[float] = None
    #: Bounded diagnostic text from the runner (never the full process output).
    diagnostics: _Optional[str] = None

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "taskId": self.task_id,
            "taskIndex": self.task_index,
            "viewId": self.view_id,
            "timestepIndex": self.timestep_index,
            "timeValue": self.time_value,
            "imageBlobId": (None if self.image_blob_id is None else _uuid_to_json(self.image_blob_id)),
            "width": self.width,
            "height": self.height,
            "format": (None if self.format is None else _enum_to_json(self.format)),
            "byteSize": self.byte_size,
            "runtimeVersion": self.runtime_version,
            "readerVersion": self.reader_version,
            "renderSeconds": self.render_seconds,
            "diagnostics": self.diagnostics,
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "ParaviewRenderResult":
        """Reads the wire object of a value document."""
        return cls(
            task_id=data.get("taskId"),
            task_index=data.get("taskIndex"),
            view_id=data.get("viewId"),
            timestep_index=data.get("timestepIndex"),
            time_value=data.get("timeValue"),
            image_blob_id=(None if data.get("imageBlobId") is None else _uuid_from_json(data.get("imageBlobId"))),
            width=data.get("width"),
            height=data.get("height"),
            format=(None if data.get("format") is None else _enum_from_json(ParaViewImageFormat, data.get("format"))),
            byte_size=data.get("byteSize"),
            runtime_version=data.get("runtimeVersion"),
            reader_version=data.get("readerVersion"),
            render_seconds=data.get("renderSeconds"),
            diagnostics=data.get("diagnostics"),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class ParaviewRuntimeRequirement:
    """What the package was produced with and what it needs to be rendered: the producing ParaView version (exact major and minor are mandatory in the version-1 compatibility policy), the producing plugin and platform (provenance), and the non-built-in plugins the state requires."""

    TYPE_ID: _ClassVar[str] = "paraview.runtimeRequirement@1"
    """The published type id this class binds."""

    #: Major version of the ParaView that produced the state.
    para_view_major: _Optional[int] = None
    #: Minor version of the ParaView that produced the state.
    para_view_minor: _Optional[int] = None
    #: Patch version of the ParaView that produced the state (informational; patch mismatch is tolerated).
    para_view_patch: _Optional[int] = None
    #: Version of the producing OmnibusCloud ParaView plugin (provenance).
    producer_plugin_version: _Optional[str] = None
    #: Runtime identifier of the producing platform, for example win-x64 (provenance).
    producer_platform: _Optional[str] = None
    #: Non-built-in plugins the state requires. Unknown names are rejected; version 1 allowlists only the bundled OmnibusCloud reader.
    plugins: list[ParaviewPluginRequirement] = _field(default_factory=list)

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "paraViewMajor": self.para_view_major,
            "paraViewMinor": self.para_view_minor,
            "paraViewPatch": self.para_view_patch,
            "producerPluginVersion": self.producer_plugin_version,
            "producerPlatform": self.producer_platform,
            "plugins": (None if self.plugins is None else [item0.to_json() for item0 in self.plugins]),
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "ParaviewRuntimeRequirement":
        """Reads the wire object of a value document."""
        return cls(
            para_view_major=data.get("paraViewMajor"),
            para_view_minor=data.get("paraViewMinor"),
            para_view_patch=data.get("paraViewPatch"),
            producer_plugin_version=data.get("producerPluginVersion"),
            producer_platform=data.get("producerPlatform"),
            plugins=([] if data.get("plugins") is None else [(None if item0 is None else ParaviewPluginRequirement.from_json(item0)) for item0 in data.get("plugins")]),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class ParaviewSceneRef:
    """Blob-backed reference to an OmnibusCloud ParaView package: the saved state (.pvsm) blob, every content-addressed attachment the state refers to by logical path, the runtime requirements, and the producer's view of the timeline. The package is validated server-side independently of any plugin-side validation; the controller never uses a client absolute path."""

    TYPE_ID: _ClassVar[str] = "paraview.sceneRef@1"
    """The published type id this class binds."""

    #: Blob identifier of the saved ParaView state (.pvsm).
    state_blob_id: _Optional[_uuid.UUID] = None
    #: Lower-case hexadecimal SHA-256 digest of the state file; verified against the blob before validation.
    state_sha256: _Optional[str] = None
    #: Declared byte size of the state file.
    state_size: _Optional[int] = None
    #: Every file the state refers to, by normalized logical path, with digest, size, role, and series metadata.
    attachments: list[ParaviewAttachmentRef] = _field(default_factory=list)
    #: Producing ParaView version and required plugins.
    runtime: _Optional[ParaviewRuntimeRequirement] = None
    #: The timeline (TimeKeeper timestep values) as the producer saw it. The state's own TimeKeeper is authoritative when the state carries one; the validation report records the resolved timeline. Empty for a static scene.
    timestep_values: list[float] = _field(default_factory=list)
    #: The producer's package manifest (com.omnibuscloud.paraview-package) as opaque provenance, bounded in size. It never drives a controller decision — the typed members above do.
    package_manifest_json: _Optional[str] = None

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "stateBlobId": (None if self.state_blob_id is None else _uuid_to_json(self.state_blob_id)),
            "stateSha256": self.state_sha256,
            "stateSize": self.state_size,
            "attachments": (None if self.attachments is None else [item0.to_json() for item0 in self.attachments]),
            "runtime": (None if self.runtime is None else self.runtime.to_json()),
            "timestepValues": (None if self.timestep_values is None else list(self.timestep_values)),
            "packageManifestJson": self.package_manifest_json,
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "ParaviewSceneRef":
        """Reads the wire object of a value document."""
        return cls(
            state_blob_id=(None if data.get("stateBlobId") is None else _uuid_from_json(data.get("stateBlobId"))),
            state_sha256=data.get("stateSha256"),
            state_size=data.get("stateSize"),
            attachments=([] if data.get("attachments") is None else [(None if item0 is None else ParaviewAttachmentRef.from_json(item0)) for item0 in data.get("attachments")]),
            runtime=(None if data.get("runtime") is None else ParaviewRuntimeRequirement.from_json(data.get("runtime"))),
            timestep_values=([] if data.get("timestepValues") is None else list(data.get("timestepValues"))),
            package_manifest_json=data.get("packageManifestJson"),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


@_dataclass(kw_only=True)
class ParaviewValidationReport:
    """Outcome of ParaView.Validate: whether the package, state, and options are admissible, every error and warning found, the subsetting fallbacks recorded, and the resolved rendering plan (view, timeline, timestep indices, output size) that ParaView.Split turns into tasks."""

    TYPE_ID: _ClassVar[str] = "paraview.validationReport@1"
    """The published type id this class binds."""

    #: True when no error was found; Split refuses an invalid report.
    is_valid: _Optional[bool] = None
    #: Permanent input failures (the job must not retry).
    errors: list[str] = _field(default_factory=list)
    #: Non-fatal findings.
    warnings: list[str] = _field(default_factory=list)
    #: Series groups that fell back to full-set transfer because their format gives no per-timestep association.
    fallbacks: list[str] = _field(default_factory=list)
    #: Digest of the whole package (state + attachments) — the first component of every task identity.
    package_digest: _Optional[str] = None
    #: Registration name of the view that will be rendered.
    resolved_view_id: _Optional[str] = None
    #: Timestep indices that will be rendered, in render order.
    resolved_timestep_indices: list[int] = _field(default_factory=list)
    #: The resolved timeline (TimeKeeper values); empty for a static scene.
    timestep_values: list[float] = _field(default_factory=list)
    #: Number of attachments in the package.
    attachment_count: _Optional[int] = None
    #: Sum of the declared attachment sizes plus the state size.
    total_attachment_bytes: _Optional[int] = None
    #: Distinct proxy types the state instantiates, as group/type, sorted.
    proxy_types: list[str] = _field(default_factory=list)
    #: Plugin requirements of the package, as name@version.
    required_plugins: list[str] = _field(default_factory=list)
    #: The ParaView runtime version the controller will render with.
    runtime_version: _Optional[str] = None
    #: Resolved output width in pixels.
    width: _Optional[int] = None
    #: Resolved output height in pixels.
    height: _Optional[int] = None
    #: Resolved output format.
    format: _Optional[ParaViewImageFormat] = None

    def to_json(self) -> dict[str, _Any]:
        """The wire object of this value (camelCase, enum names, None omitted)."""
        return _omit_none({
            "isValid": self.is_valid,
            "errors": (None if self.errors is None else list(self.errors)),
            "warnings": (None if self.warnings is None else list(self.warnings)),
            "fallbacks": (None if self.fallbacks is None else list(self.fallbacks)),
            "packageDigest": self.package_digest,
            "resolvedViewId": self.resolved_view_id,
            "resolvedTimestepIndices": (None if self.resolved_timestep_indices is None else list(self.resolved_timestep_indices)),
            "timestepValues": (None if self.timestep_values is None else list(self.timestep_values)),
            "attachmentCount": self.attachment_count,
            "totalAttachmentBytes": self.total_attachment_bytes,
            "proxyTypes": (None if self.proxy_types is None else list(self.proxy_types)),
            "requiredPlugins": (None if self.required_plugins is None else list(self.required_plugins)),
            "runtimeVersion": self.runtime_version,
            "width": self.width,
            "height": self.height,
            "format": (None if self.format is None else _enum_to_json(self.format)),
        })

    @classmethod
    def from_json(cls, data: dict[str, _Any]) -> "ParaviewValidationReport":
        """Reads the wire object of a value document."""
        return cls(
            is_valid=data.get("isValid"),
            errors=([] if data.get("errors") is None else list(data.get("errors"))),
            warnings=([] if data.get("warnings") is None else list(data.get("warnings"))),
            fallbacks=([] if data.get("fallbacks") is None else list(data.get("fallbacks"))),
            package_digest=data.get("packageDigest"),
            resolved_view_id=data.get("resolvedViewId"),
            resolved_timestep_indices=([] if data.get("resolvedTimestepIndices") is None else list(data.get("resolvedTimestepIndices"))),
            timestep_values=([] if data.get("timestepValues") is None else list(data.get("timestepValues"))),
            attachment_count=data.get("attachmentCount"),
            total_attachment_bytes=data.get("totalAttachmentBytes"),
            proxy_types=([] if data.get("proxyTypes") is None else list(data.get("proxyTypes"))),
            required_plugins=([] if data.get("requiredPlugins") is None else list(data.get("requiredPlugins"))),
            runtime_version=data.get("runtimeVersion"),
            width=data.get("width"),
            height=data.get("height"),
            format=(None if data.get("format") is None else _enum_from_json(ParaViewImageFormat, data.get("format"))),
        )

    def to_parameter(self) -> dict[str, _Any]:
        """This value as a job request parameter of kind "document"."""
        return {"kind": "document", "type": self.TYPE_ID, "value": self.to_json()}


DOCUMENT_TYPES = {
    "paraview.attachmentRef@1": ParaviewAttachmentRef,
    "paraview.frameSelection@1": ParaviewFrameSelection,
    "paraview.outputOptions@1": ParaviewOutputOptions,
    "paraview.pluginRequirement@1": ParaviewPluginRequirement,
    "paraview.renderResult@1": ParaviewRenderResult,
    "paraview.runtimeRequirement@1": ParaviewRuntimeRequirement,
    "paraview.sceneRef@1": ParaviewSceneRef,
    "paraview.validationReport@1": ParaviewValidationReport,
}
"""Type id -> dataclass, for reading value documents by their declared type."""


def from_value_document(document: dict[str, _Any]) -> _Any:
    """Reads a value document (schema v1) of a type this module binds; primitives pass through."""
    kind = document.get("kind")
    if kind == "null":
        return None
    if kind != "document":
        return document.get("value")
    type_id = document.get("type")
    binding = DOCUMENT_TYPES.get(type_id)
    if binding is None:
        raise KeyError(f"document type {type_id!r} is not part of the {COMPONENT} vocabulary")
    return binding.from_json(document.get("value") or {})


__all__ = [
    "COMPONENT",
    "TYPE_IDS",
    "DOCUMENT_TYPES",
    "from_value_document",
    "ParaViewAttachmentRole",
    "ParaViewFrameSelectionMode",
    "ParaViewImageFormat",
    "ParaviewAttachmentRef",
    "ParaviewFrameSelection",
    "ParaviewOutputOptions",
    "ParaviewPluginRequirement",
    "ParaviewRenderResult",
    "ParaviewRuntimeRequirement",
    "ParaviewSceneRef",
    "ParaviewValidationReport",
]
